app/config/AppConfig.scala
app/controllers/SignOutController.scala
app/views/headerFooterTemplate/BeforeBodyContent.scala.html
app/views/headerFooterTemplate/Layout.scala.html
app/views/templates/helpers/BetaBar.scala.html
conf/app.routes
project/plugins.sbt
test/config/AppConfigSpec.scala
test/config/MockAppConfig.scala
test/controllers/SignOutControllerTest.scala
test/views/templates/helpers/BetaBarViewSpec.scala

[SASS-639] https://jira.tools.tax.service.gov.uk/browse/SASS-607

[SASS-639] differentiate url redirect link by actor

---

app/views/expenses/CheckEmploymentExpensesView.scala.html
conf/messages
conf/messages.cy
it/controllers/CheckEmploymentExpensesControllerISpec.scala

SASS-702 - Added content fixes

---

app/views/employment/EmploymentDetailsView.scala.html
conf/messages
conf/messages.cy
it/controllers/EmploymentDetailsControllerISpec.scala

Remove compant director field
[SASS-701](https://jira.tools.tax.service.gov.uk/browse/SASS-582)

Remove company director field from view

---

app/controllers/employment/CheckYourBenefitsController.scala
app/views/employment/CheckYourBenefitsView.scala.html
conf/messages
conf/messages.cy
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
test/controllers/employment/CheckYourBenefitsControllerSpec.scala

Updated heading/title to be agent/individual specific
https://jira.tools.tax.service.gov.uk/browse/SASS-583

Sass 583: Updated heading/title to be agent/individual specific

---

it/controllers/employment/CheckEmploymentExpensesControllerISpec.scala
it/controllers/employment/EmploymentDetailsControllerISpec.scala

Re-adding the welsh tests for expenses/details

Re-adding the welsh tests for expenses/details

---

app/assets/stylesheets/application.scss
app/controllers/employment/CheckYourBenefitsController.scala
app/controllers/employment/EmploymentDetailsAndBenefitsController.scala
app/views/employment/EmploymentDetailsAndBenefitsView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/employment/EmploymentDetailsAndBenefitsControllerISpec.scala
test/controllers/employment/EmploymentDetailsAndBenefitsControllerSpec.scala

Add a new summary page for a particular employment
[SASS-750](https://jira.tools.tax.service.gov.uk/browse/SASS-729)

add individual employment summary page

---

app/views/authErrorPages/IndividualUnauthorisedView.scala.html
app/views/authErrorPages/UnauthorisedUserErrorPageView.scala.html
app/views/authErrorPages/YouNeedAgentServicesView.scala.html
app/views/employment/CheckYourBenefitsView.scala.html
app/views/headerFooterTemplate/Layout.scala.html
app/views/templates/InternalServerErrorTemplate.scala.html
app/views/templates/NotFoundTemplate.scala.html
app/views/templates/ServiceUnavailableTemplate.scala.html
app/views/templates/TaxYearErrorTemplate.scala.html
conf/messages
conf/messages.cy
test/config/MessagesSpec.scala
test/utils/ViewTest.scala

SASS-756 added code for message clean up

---

conf/app.routes
it/controllers/employment/CheckEmploymentExpensesControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
it/controllers/employment/EmploymentDetailsAndBenefitsControllerISpec.scala
it/controllers/employment/EmploymentDetailsControllerISpec.scala

Update the employment urls to remove the "your"
https://jira.tools.tax.service.gov.uk/browse/SASS-818

SASS-818: Update urls to remove the your

---

app/views/authErrorPages/AgentAuthErrorPageView.scala.html
conf/messages
conf/messages.cy
it/controllers/errors/AgentAuthErrorControllerISpec.scala
it/utils/ViewHelpers.scala
test/utils/ViewTest.scala
test/views/authErrorPages/AgentAuthErrorPageViewSpec.scala

SASS-872 - Added client-utr link to agent authorisation error page

---

app/audit/ViewEmploymentBenefitsAudit.scala
app/controllers/employment/CheckYourBenefitsController.scala
test/audit/ViewEmploymentBenefitsSpec.scala
test/controllers/employment/CheckYourBenefitsControllerSpec.scala

Adding view employment benefits audit event
https://jira.tools.tax.service.gov.uk/browse/SASS-822

SASS-822: Adding view employment benefits audit event

---

conf/application.conf

Removal of default-src from the csp filter config
[SASS-904](https://jira.tools.tax.service.gov.uk/browse/SASS-728)

Sass 904 -  Removal of default-src from csp filter config

---

conf/application.conf

Turning off metrics locally in our repos but enabling in app-config-base
[SASS-939](https://jira.tools.tax.service.gov.uk/browse/SASS-899)

[SASS-939] - turning off metrics locally

---

app/config/AppConfig.scala
app/config/ConfigKeys.scala
conf/application.conf
it/utils/IntegrationTest.scala
test/config/AppConfigSpec.scala

https://jira.tools.tax.service.gov.uk/browse/SASS-950

SASS-950 - Refactored how microservice urls are setup in AppConfig

---

build.sbt
conf/application.conf
project/AppDependencies.scala

Added HTTPOnly cookie flag to app conf to fix existing ZAP Issue
[SASS-879](https://jira.tools.tax.service.gov.uk/browse/SASS-879)

SASS-879 : Added HTTPOnly cookie flag to App Conf

---

app/controllers/employment/OtherPaymentsController.scala
app/controllers/predicates/InYearAction.scala
app/models/mongo/EmploymentUserData.scala
app/repositories/EmploymentUserDataRepository.scala
app/services/EmploymentSessionService.scala
app/views/employment/CheckEmploymentDetailsView.scala.html
app/views/employment/OtherPaymentsView.scala.html
app/views/templates/helpers/InputRadio.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/employment/CheckEmploymentDetailsControllerISpec.scala
it/controllers/employment/OtherPaymentsControllerISpec.scala
it/utils/EmploymentDatabaseHelper.scala
it/utils/IntegrationTest.scala
it/utils/ViewHelpers.scala
test/controllers/predicates/InYearActionSpec.scala

https://jira.tools.tax.service.gov.uk/browse/SASS-861

SASS-1030 - Added OtherPaymentsController to support for a user to provide payments not on P60

---

app/common/UUID.scala
app/controllers/employment/CheckEmploymentDetailsController.scala
app/controllers/employment/OtherPaymentsAmountController.scala
app/controllers/employment/OtherPaymentsController.scala
app/repositories/EmploymentUserDataIndexes.scala
app/repositories/EmploymentUserDataRepository.scala
app/repositories/Repository.scala
app/services/EmploymentSessionService.scala
app/utils/Clock.scala
app/utils/PagerDutyHelper.scala
it/controllers/employment/OtherPaymentsControllerISpec.scala
it/repositories/EmploymentUserDataRepositoryISpec.scala
it/utils/EmploymentDatabaseHelper.scala
it/utils/TestClock.scala
project/AppDependencies.scala
project/plugins.sbt
test/config/MockEmploymentSessionService.scala
test/config/MockEmploymentUserDataRepository.scala
test/controllers/employment/CheckEmploymentDetailsControllerSpec.scala
test/services/EmploymentSessionServiceSpec.scala
test/utils/TestClock.scala
test/utils/UnitTest.scala

https://jira.tools.tax.service.gov.uk/browse/SASS-1058

SASS-1058 - Refactored employment repository to support createOrUpdate

---

app/controllers/employment/EmployerNameController.scala
app/forms/employment/EmployerNameForm.scala
app/forms/validation/StringConstraints.scala
app/views/employment/CheckEmploymentDetailsView.scala.html
app/views/employment/EmployerNameView.scala.html
app/views/templates/helpers/InputText.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/employment/CheckEmploymentDetailsControllerISpec.scala
it/controllers/employment/EmployerNameControllerISpec.scala
it/utils/IntegrationTest.scala
it/utils/ViewHelpers.scala
test/forms/employment/EmployerNameFormSpec.scala
test/forms/testUtils/StringConstraintsSpec.scala

created the 'name of employer' page
[SASS-857](https://jira.tools.tax.service.gov.uk/browse/SASS-857)

SASS-1033 - Creation of 'name of your employer' page

---

app/controllers/employment/OtherPaymentsAmountController.scala
app/controllers/employment/OtherPaymentsController.scala
app/services/EmploymentSessionService.scala
conf/messages
conf/messages.cy
it/controllers/employment/OtherPaymentsAmountControllerISpec.scala
it/controllers/employment/OtherPaymentsControllerISpec.scala
it/utils/IntegrationTest.scala
it/utils/IntegrationTestClock.scala
test/services/EmploymentSessionServiceSpec.scala
test/utils/UnitTest.scala
test/utils/UnitTestClock.scala

Content changes after demoing the ticket below.
https://jira.tools.tax.service.gov.uk/browse/SASS-1030

SASS-0000 - Minor content change

---

app/controllers/employment/PayeRefController.scala
app/forms/employment/PayeForm.scala
app/forms/validation/StringConstraints.scala
app/views/employment/CheckEmploymentDetailsView.scala.html
app/views/employment/PayeRefView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/employment/CheckEmploymentDetailsControllerISpec.scala
it/controllers/employment/PayeRefControllerISpec.scala
it/utils/IntegrationTest.scala
project/AppDependencies.scala
test/forms/employment/PayeRefFormSpec.scala
test/forms/testUtils/StringConstraintsSpec.scala

Creation of PAYE ref page + new form
[SASS-1082]( https://jira.tools.tax.service.gov.uk/browse/SASS-858)

create PAYE ref page

---

app/controllers/employment/CheckEmploymentExpensesController.scala
app/models/employment/Deductions.scala
app/models/employment/EmploymentExpenses.scala
app/models/employment/StudenLoans.scala
it/controllers/employment/CheckEmploymentDetailsControllerISpec.scala
it/controllers/employment/EmploymentSummaryControllerISpec.scala
it/controllers/employment/EmploymentTaxControllerISpec.scala
it/utils/IntegrationTest.scala
test/controllers/employment/EmploymentSummaryControllerSpec.scala
test/services/EmploymentSessionServiceSpec.scala
test/utils/UnitTest.scala

https://jira.tools.tax.service.gov.uk/browse/SASS-1067

SASS-1067 - Added additional data items in employment models

---

app/controllers/employment/EmploymentSummaryController.scala
app/models/employment/AllEmploymentData.scala
app/services/EmploymentSessionService.scala
app/utils/DateTimeUtil.scala
app/utils/ViewUtils.scala
app/views/employment/MultipleEmploymentsSummaryView.scala.html
app/views/employment/SingleEmploymentSummaryViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/employment/MultipleEmploymentSummaryEOYControllerISpec.scala
it/controllers/employment/SingleEmploymentSummaryEOYControllerISpec.scala
project/AppDependencies.scala
test/controllers/employment/EmploymentSummaryControllerSpec.scala
test/services/EmploymentSessionServiceSpec.scala
test/utils/DateTimeUtilSpec.scala

Rework the employment summary page for EOY functionality
- New pages for multiple and single EOY
- New session service methods to handle returning the latest employments/expenses
- Updated pages to use checks for customer data
https://jira.tools.tax.service.gov.uk/browse/SASS-930

Sass 930 view

---

app/controllers/employment/PayeRefController.scala
app/models/employment/EmploymentDetailsViewModel.scala
app/views/employment/CheckEmploymentDetailsView.scala.html
conf/messages
conf/messages.cy
it/controllers/employment/CheckEmploymentDetailsControllerISpec.scala

https://jira.tools.tax.service.gov.uk/browse/SASS-1056

SASS-1056 - Add Employment start date line item to employment cya page

---

app/controllers/employment/AddEmploymentController.scala
it/controllers/employment/AddEmploymentControllerISpec.scala
it/utils/ViewHelpers.scala

get session data

---

app/services/DeleteOrIgnoreEmploymentService.scala
test/config/MockDeleteOrIgnoreEmploymentService.scala
test/services/DeleteOrIgnoreEmploymentServiceSpec.scala

removed all parameter from delete employment orchestration
https://jira.tools.tax.service.gov.uk/browse/SASS-1107

removed all from delete employment orchestration

---

app/controllers/employment/CheckEmploymentExpensesController.scala
app/controllers/employment/EmployerPayAmountController.scala
app/controllers/employment/EmploymentTaxController.scala
app/controllers/employment/OtherPaymentsAmountController.scala
app/controllers/employment/PayeRefController.scala
app/views/employment/EmploymentTaxView.scala.html
it/connectors/IncomeTaxUserDataConnectorSpec.scala
it/controllers/employment/AddEmploymentControllerISpec.scala
it/controllers/employment/CheckEmploymentDetailsControllerISpec.scala
it/controllers/employment/CheckEmploymentExpensesControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
it/controllers/employment/EmployerPayAmountControllerISpec.scala
it/controllers/employment/EmploymentDetailsAndBenefitsControllerISpec.scala
it/controllers/employment/EmploymentTaxControllerISpec.scala
it/controllers/employment/OtherPaymentsAmountControllerISpec.scala
it/controllers/employment/PayeRefControllerISpec.scala
it/utils/IntegrationTest.scala
test/config/MockEmploymentSessionService.scala
test/controllers/employment/EmploymentTaxControllerSpec.scala

Added Logic around pre-filling inputs
[SASS-1086](https://jira.tools.tax.service.gov.uk/browse/SASS-1086)

Sass 1153a

---

app/controllers/employment/RemoveEmploymentController.scala
app/views/employment/RemoveEmploymentView.scala.html
conf/messages
conf/messages.cy
it/controllers/employment/RemoveEmploymentControllerISpec.scala
test/config/MockEmploymentSessionService.scala
test/controllers/employment/RemoveEmploymentControllerSpec.scala

content changes from demo
[SASS-938](https://jira.tools.tax.service.gov.uk/browse/SASS-938)

updated remove paragraph text and added check for last employment

---

app/controllers/employment/CarVanFuelBenefitsController.scala
app/controllers/employment/CheckYourBenefitsController.scala
app/models/employment/Benefits.scala
app/models/employment/BenefitsViewModel.scala
app/models/employment/CarVanFuelModel.scala
app/views/employment/CarVanFuelBenefitsView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/employment/CarVanFuelBenefitsControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
it/utils/ViewHelpers.scala
test/models/EmploymentBenefitsModelSpec.scala
test/services/EmploymentSessionServiceSpec.scala

Sass 1130b

---

app/services/EmploymentSessionService.scala
it/controllers/employment/CheckEmploymentDetailsControllerISpec.scala
it/controllers/employment/EmploymentSummaryControllerISpec.scala
it/controllers/employment/SingleEmploymentSummaryEOYControllerISpec.scala
project/AppDependencies.scala
test/services/EmploymentSessionServiceSpec.scala

updated navigation to align with E3.1 flow
[SASS-934](https://jira.tools.tax.service.gov.uk/browse/SASS-934)

SASS-1218 - navigation for employment details EOY

---

app/controllers/benefits/CarVanFuelBenefitsController.scala
app/controllers/benefits/ReceiveAnyBenefitsController.scala
app/controllers/employment/CheckYourBenefitsController.scala
app/controllers/employment/EmployerNameController.scala
app/models/employment/AllEmploymentData.scala
app/models/employment/Benefits.scala
app/models/employment/BenefitsViewModel.scala
app/views/benefits/ReceiveAnyBenefitsView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/ReceiveAnyBenefitsControllerISpec.scala
it/controllers/employment/CarVanFuelBenefitsControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
project/AppDependencies.scala
test/models/EmploymentBenefitsModelSpec.scala

- Creating the did you receive benefits page
- Routing from CYA to the above page
- Routing from the benefits/details page to this page if theres no benefits
https://jira.tools.tax.service.gov.uk/browse/SASS-1043

Sass 1121c

---

app/controllers/benefits/CarVanFuelBenefitsController.scala
it/controllers/employment/CarVanFuelBenefitsControllerISpec.scala

- Updating the redirects
SASS-1130

changed the redirects on the car van fuel controller

---

app/controllers/benefits/CompanyVanBenefitsController.scala
app/controllers/employment/CompanyCarBenefitsController.scala
app/views/benefits/CompanyVanBenefitsView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/CompanyVanBenefitsControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
test/controllers/employment/CompanyCarBenefitsControllerSpec.scala

created radio button page for company van benefits
[SASS-1165](https://jira.tools.tax.service.gov.uk/browse/SASS-1165)

Sass 1243 - company van benefits radio button page

---

app/views/employment/CheckYourBenefitsView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
app/views/employment/MultipleEmploymentsSummaryView.scala.html
conf/app.routes
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
it/controllers/employment/EmploymentSummaryControllerISpec.scala
it/controllers/employment/MultipleEmploymentSummaryEOYControllerISpec.scala
project/AppDependencies.scala

- Updating the subheadings on the benefits/multiple employment details page to be h2 tags instead of p tags
- Updating dependencies
https://jira.tools.tax.service.gov.uk/browse/SASS-1256

SASS-1256: Updated headings to be h2 tags instead of p tags

---

app/controllers/employment/CompanyCarFuelBenefitsController.scala
app/views/employment/CheckYourBenefitsViewEOY.scala.html
app/views/employment/CompanyCarFuelBenefitsView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
it/controllers/employment/CompanyCarFuelBenefitsControllerISpec.scala

Created fuel benefit for company car radio button EOY page.
https://jira.tools.tax.service.gov.uk/browse/SASS-1163

SASS-1163 added radio button for car company fuel

---

app/controllers/employment/CompanyCarBenefitsController.scala
conf/messages
conf/messages.cy
it/controllers/employment/CompanyCarBenefitsControllerISpec.scala

Content fixes from demo
[SASS-1131](https://jira.tools.tax.service.gov.uk/browse/SASS-1131)

Sass 1131 content fixes

---

app/views/employment/MultipleEmploymentsSummaryView.scala.html
app/views/employment/SingleEmploymentSummaryViewEOY.scala.html
it/controllers/employment/MultipleEmploymentSummaryEOYControllerISpec.scala
it/controllers/employment/SingleEmploymentSummaryEOYControllerISpec.scala
project/AppDependencies.scala

Added aria-hidden and updated hidden text on change/remove links to fix axe-core issue
[SASS-1202](https://jira.tools.tax.service.gov.uk/browse/SASS-1202)

SASS-1202 addressed axe-core issue: identical-link-same-purpose

---

app/controllers/employment/EmploymentSummaryController.scala
app/views/employment/CheckEmploymentExpensesView.scala.html
app/views/employment/EmployerNameView.scala.html
app/views/employment/PayeRefView.scala.html
app/views/templates/helpers/InputText.scala.html
test/controllers/employment/EmploymentSummaryControllerSpec.scala

Uplift of Char limits and content changes to reflect charity names.
[SASS-1253](https://jira.tools.tax.service.gov.uk/browse/SASS-1253)

SASS-1253 : Char limits raised and content updated on name pages

---

app/controllers/employment/EmployerPayrollIdController.scala
app/forms/employment/EmployerPayrollIdForm.scala
app/forms/validation/StringConstraints.scala
app/models/employment/AllEmploymentData.scala
app/models/employment/EmploymentDetailsViewModel.scala
app/models/mongo/EmploymentCYAModel.scala
app/services/RedirectService.scala
app/views/employment/CheckEmploymentDetailsView.scala.html
app/views/employment/EmployerPayrollIdView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/employment/CheckEmploymentDetailsControllerISpec.scala
it/controllers/employment/EmployerPayrollIdControllerISpec.scala
it/controllers/employment/StillWorkingForEmployerControllerISpec.scala
it/utils/IntegrationTest.scala
test/audit/ViewEmploymentDetailsSpec.scala
test/controllers/employment/CheckEmploymentDetailsControllerSpec.scala
test/services/RedirectServiceSpec.scala

- Creating the new Employment payrollId page
- Linking the page in the flow and from CYA
https://jira.tools.tax.service.gov.uk/browse/SASS-1235

SASS-1235: Adding employer payroll id page

---

app/controllers/employment/EmployerPayrollIdController.scala
app/views/employment/EmployerPayrollIdView.scala.html
conf/messages
conf/messages.cy
it/controllers/employment/EmployerPayrollIdControllerISpec.scala

Amended the view to have dynamic content after feedback from the demo
[SASS-1283](https://jira.tools.tax.service.gov.uk/browse/SASS-1235)

Amended the view after demo

---

it/repositories/EmploymentUserDataRepositoryISpec.scala
it/repositories/ExpensesUserDataRepositoryISpec.scala

added await to futures so that tests pass

updated tests in user repositories to fix mongo exception error

---

app/controllers/employment/EmployerPayrollIdController.scala
app/views/employment/EmployerPayrollIdView.scala.html
conf/messages
conf/messages.cy
it/controllers/employment/EmployerPayrollIdControllerISpec.scala
it/repositories/EmploymentUserDataRepositoryISpec.scala
it/repositories/ExpensesUserDataRepositoryISpec.scala

Amending lost Github commit history - Sass fixing test

---

app/controllers/benefits/CarFuelBenefitsAmountController.scala
app/views/benefits/CarFuelBenefitsAmountView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
app/views/employment/OtherPaymentsAmountView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/CarFuelBenefitsAmountControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala

- Adding new Car Fuel Amount page
- Linking the page from the CYA benefits view
https://jira.tools.tax.service.gov.uk/browse/SASS-1164
- [x ]  Have you assigned yourself to the PR?
- [x ]  Have you checked to ensure all dependencies are up to date?
- [x ]  Have you checked to ensure its been rebased against the current version of master?
- [x ]  Have you run the journey tests?
- [x ]  Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?

added car fuel amount page

---

app/controllers/benefits/CompanyVanFuelBenefitsAmountController.scala
app/views/benefits/CompanyVanFuelBenefitsAmountView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/CompanyVanFuelBenefitsAmountControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala

- Creating the company van fuel benefit amount EOY page
- Routing from CYA page change link to the page
https://jira.tools.tax.service.gov.uk/browse/SASS-1403

Sass 1403: Create company van fuel benefit amount EOY page

---

app/controllers/benefits/AccommodationRelocationBenefitsController.scala
app/models/employment/AccommodationRelocationModel.scala
app/models/employment/Benefits.scala
app/models/employment/BenefitsViewModel.scala
app/services/EncryptionService.scala
app/services/RedirectService.scala
app/views/benefits/AccommodationRelocationBenefitsView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/AccommodationRelocationControllerISpec.scala
it/controllers/benefits/CarFuelBenefitsAmountControllerISpec.scala
it/controllers/benefits/CarVanFuelBenefitsControllerISpec.scala
it/controllers/benefits/CompanyCarBenefitsAmountControllerISpec.scala
it/controllers/benefits/CompanyCarBenefitsControllerISpec.scala
it/controllers/benefits/CompanyCarFuelBenefitsControllerISpec.scala
it/controllers/benefits/CompanyVanBenefitsAmountControllerISpec.scala
it/controllers/benefits/CompanyVanBenefitsControllerISpec.scala
it/controllers/benefits/MileageBenefitAmountControllerISpec.scala
it/controllers/benefits/ReceivedOwnCarMileageBenefitControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
it/repositories/EmploymentUserDataRepositoryISpec.scala
test/models/EmploymentBenefitsModelSpec.scala
test/services/EmploymentSessionServiceSpec.scala
test/services/RedirectServiceSpec.scala

Create did you get accommodation or relocation employment benefits radio button EOY page
[SASS-1312](https://jira.tools.tax.service.gov.uk/browse/SASS-1312)

SASS-1312 accommodation and relocation

---

app/controllers/benefits/LivingAccommodationBenefitsController.scala
app/models/employment/AccommodationRelocationModel.scala
app/services/RedirectService.scala
app/views/benefits/LivingAccommodationBenefitsView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/LivingAccommodationBenefitsControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
it/utils/IntegrationTest.scala
test/services/RedirectServiceSpec.scala

- added the radio button page for living accommodation benefits
- updated TODOs and tests that redirect to that page
[SASS-1315](https://jira.tools.tax.service.gov.uk/browse/SASS-1315)

SASS-1400 - Added living accommodation benefits radio button page

---

app/models/benefits/UtilitiesAndServicesModel.scala
app/models/employment/Benefits.scala
app/models/employment/BenefitsViewModel.scala
app/services/EncryptionService.scala
app/services/RedirectService.scala
app/views/employment/CheckYourBenefitsViewEOY.scala.html
it/repositories/EmploymentUserDataRepositoryISpec.scala
test/models/EmploymentBenefitsModelSpec.scala
test/models/UtilitiesAndServicesModelSpec.scala
test/services/RedirectServiceSpec.scala

Head start on redirects and model ready for the utilities journey
https://jira.tools.tax.service.gov.uk/browse/SASS-1443

Sass 1443 utilities redirects

---

app/controllers/benefits/EntertainingBenefitsController.scala
app/models/employment/TravelEntertainmentModel.scala
app/services/RedirectService.scala
app/views/benefits/EntertainingBenefitsView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/EntertainingBenefitsControllerISpec.scala
it/controllers/benefits/EntertainmentBenefitsAmountControllerISpec.scala
it/controllers/benefits/IncidentalCostsBenefitsAmountControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
test/models/employment/TravelEntertainmentModelSpec.scala
test/services/RedirectServiceSpec.scala

Create entertainment employment benefits radio button EOY page
[SASS-1381](https://jira.tools.tax.service.gov.uk/browse/SASS-1381)

SASS-1381 Entertaining benefits radio page

---

app/controllers/benefits/EmployerProvidedServicesBenefitsController.scala
app/models/benefits/UtilitiesAndServicesModel.scala
app/services/RedirectService.scala
app/views/benefits/EmployerProvidedServicesView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/EmployerProvidedServicesBenefitsControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
test/models/UtilitiesAndServicesModelSpec.scala
test/services/RedirectServiceSpec.scala

- Create services provided by employer benefits radio button EOY page
- Linking the page from the CYA screen
- Updating some redirect methods to hit the page, and adding missed changes to hit the first utilities page
https://jira.tools.tax.service.gov.uk/browse/SASS-1447

Sass 1447: Create services provided by employer benefits radio button EOY page

---

app/views/benefits/EmployerProvidedServicesView.scala.html
conf/messages
conf/messages.cy
it/controllers/benefits/EmployerProvidedServicesBenefitsControllerISpec.scala

[SASS-1447](https://jira.tools.tax.service.gov.uk/browse/SASS-1447)

@SASS-1447 - Removes hint text and appends it to main paragraph.

---

app/controllers/benefits/EmployerProvidedServicesBenefitsAmountController.scala
app/controllers/benefits/ProfessionalSubscriptionsBenefitsController.scala
app/models/benefits/UtilitiesAndServicesModel.scala
app/services/RedirectService.scala
app/views/benefits/ProfessionalSubscriptionsBenefitsView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/EmployerProvidedServicesBenefitsAmountControllerISpec.scala
it/controllers/benefits/ProfessionalSubscriptionsBenefitsControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
test/models/UtilitiesAndServicesModelSpec.scala
test/services/RedirectServiceSpec.scala

added radio button page for professional fees and subscriptions benefits
[SASS-1449](https://jira.tools.tax.service.gov.uk/browse/SASS-1449)

SASS-1508 - Professional fees and subscriptions radio button page

---

app/controllers/benefits/TelephoneBenefitsController.scala
app/models/benefits/UtilitiesAndServicesModel.scala
app/services/RedirectService.scala
app/views/benefits/TelephoneBenefitsView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/OtherServicesBenefitsControllerISpec.scala
it/controllers/benefits/TelephoneBenefitsControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
test/models/UtilitiesAndServicesModelSpec.scala
test/services/RedirectServiceSpec.scala

Addition of telephone benefits yes.no EOY radio button
https://jira.tools.tax.service.gov.uk/browse/SASS-1445

Sass 1504 - Add telephone benefits yes/no radio button page EOY 

---

app/controllers/benefits/IncidentalOvernightCostEmploymentBenefitsController.scala
app/services/RedirectService.scala
app/views/benefits/IncidentalOvernightCostEmploymentBenefitsView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/IncidentalCostsBenefitsAmountControllerISpec.scala
it/controllers/benefits/IncidentalOvernightCostEmploymentBenefitsControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
test/services/RedirectServiceSpec.scala

Create incidental overnight costs employment benefits radio button EOY page
[SASS-1379](https://jira.tools.tax.service.gov.uk/browse/SASS-1379)

Sass 1379 -Create incidental overnight costs employment benefits radio button EOY page

---

app/controllers/benefits/ProfessionalSubscriptionsBenefitsAmountController.scala
app/models/benefits/UtilitiesAndServicesModel.scala
app/views/benefits/ProfessionalSubscriptionsBenefitsAmountView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/ProfessionalSubscriptionsBenefitsAmountControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
test/models/UtilitiesAndServicesModelSpec.scala
test/services/RedirectServiceSpec.scala

Create professional fees or subscriptions employment benefits amount EOY page
[SASS-1450](https://jira.tools.tax.service.gov.uk/browse/SASS-1450)

SASS-1450 Create professional fees or subscriptions amount EOY page

---

app/controllers/benefits/TelephoneEmploymentBenefitsAmountController.scala
app/views/benefits/TelephoneEmploymentBenefitsAmountView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/TelephoneEmploymentBenefitsAmountControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala

Create telephone employment benefits amount EOY page .
[SASS-1446](https://jira.tools.tax.service.gov.uk/browse/SASS-1446)

SASS-1446 Create telephone employment benefits amount EOY page

---

app/controllers/benefits/OtherServicesBenefitsAmountController.scala
app/controllers/benefits/OtherServicesBenefitsController.scala
app/views/benefits/OtherServicesBenefitsAmountView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/OtherServicesBenefitsAmountControllerISpec.scala
it/controllers/benefits/OtherServicesBenefitsControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala

Create other service employment benefits amount EOY page
https://jira.tools.tax.service.gov.uk/browse/SASS-1452

SASS-1452 Add other services amount page

---

app/models/benefits/MedicalChildcareEducationModel.scala
app/models/employment/Benefits.scala
app/models/employment/BenefitsViewModel.scala
app/services/EncryptionService.scala
app/services/RedirectService.scala
app/views/employment/CheckYourBenefitsViewEOY.scala.html
it/repositories/EmploymentUserDataRepositoryISpec.scala
test/models/EmploymentBenefitsModelSpec.scala
test/models/benefits/MedicalChildcareEducationModelSpec.scala
test/models/benefits/UtilitiesAndServicesModelSpec.scala
test/services/RedirectServiceSpec.scala

[SASS-1551](https://jira.tools.tax.service.gov.uk/browse/SASS-1551)

SASS-1551 - Update redirect service for medical section

---

app/controllers/benefits/accommodationAndRelocation/QualifyingRelocationBenefitsController.scala
app/models/benefits/Benefits.scala
app/models/benefits/BenefitsViewModel.scala
app/models/benefits/IncomeTaxAndCostsModel.scala
app/services/EncryptionService.scala
app/services/RedirectService.scala
app/views/employment/CheckYourBenefitsViewEOY.scala.html
it/repositories/EmploymentUserDataRepositoryISpec.scala
project/AppDependencies.scala
test/models/EmploymentBenefitsModelSpec.scala
test/models/benefits/IncomeTaxAndCostsModelSpec.scala
test/services/RedirectServiceSpec.scala

[SASS-1552](https://jira.tools.tax.service.gov.uk/browse/SASS-1552)

SASS-1552 - Update redirect service for income tax and costs section.

---

app/controllers/benefits/medicalChildcareEducation/ChildcareBenefitsController.scala
app/services/RedirectService.scala
app/views/benefits/ChildcareBenefitsView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/medicalChildcareEducation/ChildcareBenefitsControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
it/utils/IntegrationTest.scala
test/services/RedirectServiceSpec.scala

- Create childcare employment benefits radio button EOY page
- Link the page to the CYA childcare change link
https://jira.tools.tax.service.gov.uk/browse/SASS-1528

Sass 1528: Create childcare employment benefits radio button EOY page

---

app/controllers/benefits/medicalChildcareEducation/MedicalDentalChildcareBenefitsController.scala
app/controllers/benefits/utilitiesAndServices/OtherServicesBenefitsAmountController.scala
app/services/RedirectService.scala
app/views/benefits/MedicalDentalChildcareBenefitsView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/medicalChildcareEducation/MedicalDentalChildcareBenefitsControllerISpec.scala
it/controllers/benefits/utilitiesAndServices/EmployerProvidedServicesBenefitsControllerISpec.scala
it/controllers/benefits/utilitiesAndServices/OtherServicesBenefitsAmountControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
it/utils/IntegrationTest.scala
test/services/RedirectServiceSpec.scala

Create 'medical, dental, childcare, education, loans' employment benefits radio button EOY page
https://jira.tools.tax.service.gov.uk/browse/SASS-1523

SASS-1523 - add first medical, dental, childcare, education, loans page

---

app/controllers/benefits/medicalChildcareEducation/ChildcareBenefitsAmountController.scala
app/controllers/benefits/medicalChildcareEducation/ChildcareBenefitsController.scala
app/models/benefits/MedicalChildcareEducationModel.scala
app/services/RedirectService.scala
app/views/benefits/ChildcareBenefitsAmountView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/medicalChildcareEducation/ChildcareBenefitsAmountControllerISpec.scala
it/controllers/benefits/medicalChildcareEducation/ChildcareBenefitsControllerISpec.scala
it/controllers/benefits/travelAndEntertainment/IncidentalCostsBenefitsAmountControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
it/utils/IntegrationTest.scala
test/models/benefits/MedicalChildcareEducationModelSpec.scala
test/services/RedirectServiceSpec.scala

added childcare benefits amount page for EOY
[SASS-1527](https://jira.tools.tax.service.gov.uk/browse/SASS-1527)

SASS-1527 - Create childcare employment benefits amount page

---

app/controllers/benefits/medical/BeneficialLoansBenefitsController.scala
app/services/RedirectService.scala
app/views/benefits/BeneficialLoansBenefitsView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/medical/BeneficialLoansBenefitsControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
project/AppDependencies.scala
test/services/RedirectServiceSpec.scala

- Added beneficial loans question page
- Linked the page to the benefits CYA screen
https://jira.tools.tax.service.gov.uk/browse/SASS-1531

SASS-1531: Added beneficial loans question page

---

app/controllers/benefits/medical/MedicalOrDentalBenefitsAmountController.scala
app/views/benefits/MedicalOrDentalBenefitsAmountView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/medical/MedicalOrDentalBenefitsAmountControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
it/utils/IntegrationTest.scala

Added new page for medical or dental benefits amount
[SASS-1526](https://jira.tools.tax.service.gov.uk/browse/SASS-1526)

Added new page for medical or dental benefits amount

---

app/controllers/expenses/EmploymentExpensesController.scala
app/models/employment/Expenses.scala
app/models/employment/ExpensesViewModel.scala
app/services/EmploymentSessionService.scala
app/views/employment/CheckEmploymentExpensesViewEOY.scala.html
app/views/expenses/EmploymentExpensesView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/medical/MedicalDentalChildcareBenefitsControllerISpec.scala
it/controllers/employment/CheckEmploymentExpensesControllerISpec.scala
it/controllers/expenses/EmploymentExpensesControllerISpec.scala
it/utils/IntegrationTest.scala
test/services/EmploymentSessionServiceSpec.scala

Create claim employment expenses radio button EOY page
https://jira.tools.tax.service.gov.uk/browse/SASS-1537

SASS-1537  Create claim employment expenses radio button EOY page

---

app/controllers/benefits/medical/BeneficialLoansAmountController.scala
app/models/benefits/MedicalChildcareEducationModel.scala
app/views/benefits/BeneficialLoansAmountView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/medical/BeneficialLoansAmountControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
test/models/benefits/MedicalChildcareEducationModelSpec.scala
test/services/RedirectServiceSpec.scala

added beneficial loans amount page
[SASS-1532](https://jira.tools.tax.service.gov.uk/browse/SASS-1532)

SASS-1632 - beneficial loans amount page

---

app/controllers/benefits/incomeTax/IncomeTaxOrIncurredCostsBenefitsController.scala
app/models/benefits/IncomeTaxAndCostsModel.scala
app/services/RedirectService.scala
app/views/benefits/incomeTax/IncomeTaxOrIncurredCostsBenefitsView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/incomeTax/IncomeTaxOrIncurredCostsControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
it/utils/IntegrationTest.scala
test/models/benefits/IncomeTaxAndCostsModelSpec.scala
test/services/RedirectServiceSpec.scala

- Creating the Income tax or incurred costs benefits radio button page
- Linking the page to the check your benefits EOY page
https://jira.tools.tax.service.gov.uk/browse/SASS-1590

added income tax and incurred costs page

---

app/controllers/benefits/medical/MedicalDentalBenefitsController.scala
app/models/benefits/MedicalChildcareEducationModel.scala
app/services/RedirectService.scala
app/views/benefits/medical/MedicalDentalBenefitsView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/medical/MedicalDentalBenefitsControllerISpec.scala
it/controllers/benefits/medical/MedicalOrDentalBenefitsAmountControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
test/models/benefits/MedicalChildcareEducationModelSpec.scala
test/services/RedirectServiceSpec.scala

[SASS-1525](https://jira.tools.tax.service.gov.uk/browse/SASS-1525)

Implemented medical and dental insurance page.

---

app/controllers/benefits/income/IncomeTaxBenefitsController.scala
app/controllers/benefits/income/IncomeTaxOrIncurredCostsBenefitsController.scala
app/models/benefits/IncomeTaxAndCostsModel.scala
app/services/RedirectService.scala
app/views/benefits/income/IncomeTaxBenefitsView.scala.html
app/views/benefits/income/IncomeTaxOrIncurredCostsBenefitsView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/income/IncomeTaxBenefitsControllerISpec.scala
it/controllers/benefits/income/IncomeTaxOrIncurredCostsControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
test/models/benefits/IncomeTaxAndCostsModelSpec.scala
test/services/RedirectServiceSpec.scala

- Create Income Tax employment benefits radio button EOY page
- Linking the page to the benefits CYA page
- Updating the incomeTax package name to be income
https://jira.tools.tax.service.gov.uk/browse/SASS-1591

Sass 1591: Create Income Tax employment benefits radio button EOY page

---

app/controllers/benefits/income/IncurredCostsBenefitsController.scala
app/models/benefits/IncomeTaxAndCostsModel.scala
app/services/RedirectService.scala
app/views/benefits/income/IncurredCostsBenefitsView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/income/IncurredCostsBenefitsControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
test/models/benefits/IncomeTaxAndCostsModelSpec.scala
test/services/RedirectServiceSpec.scala

- Adding incurred costs benefits question page
- Linking the page to the benefits CYA page
https://jira.tools.tax.service.gov.uk/browse/SASS-1593

SASS-1593: Adding incurred costs benefits question page

---

app/controllers/benefits/income/IncurredCostsBenefitsAmountController.scala
app/models/benefits/IncomeTaxAndCostsModel.scala
app/views/benefits/income/IncurredCostsBenefitsAmountView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/income/IncurredCostsBenefitsAmountControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
test/models/benefits/IncomeTaxAndCostsModelSpec.scala

- Adding incurred costs amount page
- Linking the page to the benefits CYA page
https://jira.tools.tax.service.gov.uk/browse/SASS-1594

SASS-1594: Adding incurred costs amount page

---

app/controllers/expenses/ProfessionalFeesAndSubscriptionsExpensesController.scala
app/views/employment/CheckEmploymentExpensesViewEOY.scala.html
app/views/expenses/ProfessionalFeesAndSubscriptionsExpensesView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/employment/CheckEmploymentExpensesControllerISpec.scala
it/controllers/expenses/ProfessionalFeesAndSubscriptionsExpensesControllerISpec.scala

Professional fees and subscription radio button.
[SASS-1544](https://jira.tools.tax.service.gov.uk/browse/SASS-1544)

SASS-1544 Professional fees and subscription radio button

---

app/controllers/benefits/reimbursed/ReimbursedCostsVouchersAndNonCashBenefitsController.scala
app/models/benefits/ReimbursedCostsVouchersAndNonCashModel.scala
app/services/RedirectService.scala
app/views/benefits/reimbursed/ReimbursedCostsVouchersAndNonCashBenefitsView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/reimbursed/ReimbursedCostsVouchersAndNonCashBenefitsControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
it/utils/IntegrationTest.scala
test/models/benefits/ReimbursedCostsVouchersAndNonCashModelSpec.scala
test/services/RedirectServiceSpec.scala

- Create 'Reimbursed costs, vouchers or non-cash' employment benefits radio button EOY page
- Linked page to the benefits CYA page
https://jira.tools.tax.service.gov.uk/browse/SASS-1647

SASS-1647: Added reimbursed section question page

---

app/controllers/benefits/medical/BeneficialLoansAmountController.scala
app/controllers/benefits/medical/BeneficialLoansBenefitsController.scala
app/controllers/benefits/medical/ChildcareBenefitsAmountController.scala
app/controllers/benefits/medical/ChildcareBenefitsController.scala
app/controllers/benefits/medical/EducationalServicesBenefitsAmountController.scala
app/controllers/benefits/medical/EducationalServicesBenefitsController.scala
app/controllers/benefits/medical/MedicalDentalBenefitsController.scala
app/controllers/benefits/medical/MedicalDentalChildcareBenefitsController.scala
app/controllers/benefits/medical/MedicalOrDentalBenefitsAmountController.scala
app/services/RedirectService.scala
app/views/employment/CheckYourBenefitsViewEOY.scala.html
it/controllers/benefits/medical/BeneficialLoansAmountControllerISpec.scala
it/controllers/benefits/medical/BeneficialLoansBenefitsControllerISpec.scala
it/controllers/benefits/medical/ChildcareBenefitsAmountControllerISpec.scala
it/controllers/benefits/medical/ChildcareBenefitsControllerISpec.scala
it/controllers/benefits/medical/EducationalServicesBenefitsAmountControllerISpec.scala
it/controllers/benefits/medical/EducationalServicesBenefitsControllerISpec.scala
it/controllers/benefits/medical/MedicalDentalBenefitsControllerISpec.scala
it/controllers/benefits/medical/MedicalDentalChildcareBenefitsControllerISpec.scala
it/controllers/benefits/medical/MedicalOrDentalBenefitsAmountControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala

https://jira.tools.tax.service.gov.uk/browse/SASS-1646

SASS-1688 Added navigation for medical section

---

app/controllers/benefits/reimbursed/TaxableCostsBenefitsAmountController.scala
app/models/benefits/BenefitsViewModel.scala
app/models/benefits/ReimbursedCostsVouchersAndNonCashModel.scala
app/views/benefits/reimbursed/TaxableCostsBenefitsAmountView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/reimbursed/TaxableCostsBenefitsAmountControllerISpec.scala
it/controllers/benefits/travel/IncidentalCostsBenefitsAmountControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
test/config/MessagesSpec.scala
test/models/benefits/ReimbursedCostsVouchersAndNonCashModelSpec.scala
test/services/RedirectServiceSpec.scala

Creates taxable employment benefits amount EOY page.
[SASS-1651](https://jira.tools.tax.service.gov.uk/browse/SASS-1651)

SASS-1651 - Create taxable employment benefits amount EOY page.

---

app/controllers/expenses/TravelAndOvernightAmountController.scala
app/views/employment/CheckEmploymentExpensesViewEOY.scala.html
app/views/expenses/TravelAndOvernightAmountView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/employment/CheckEmploymentExpensesControllerISpec.scala
it/controllers/expenses/BusinessTravelOvernightExpensesControllerISpec.scala
it/controllers/expenses/TravelAndOvernightAmountControllerISpec.scala

[SASS-1541](https://jira.tools.tax.service.gov.uk/browse/SASS-1541)

[SASS-1627] - Business travel and overnight stays amount page + tests

---

app/views/employment/MultipleEmploymentsSummaryView.scala.html
app/views/employment/SingleEmploymentSummaryView.scala.html
it/controllers/employment/EmploymentSummaryControllerISpec.scala

SASS-1241 design pattern change for in-year summary pages
[SASS-1241](https://jira.tools.tax.service.gov.uk/browse/SASS-1241)

SASS-1241 design pattern change for in-year summary pages on Employment

---

app/controllers/expenses/OtherEquipmentController.scala
app/views/employment/CheckEmploymentExpensesViewEOY.scala.html
app/views/expenses/OtherEquipmentView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/employment/CheckEmploymentExpensesControllerISpec.scala
it/controllers/expenses/OtherEquipmentControllerISpec.scala

Implemented the other equipment radio page
[SASS-1546](https://jira.tools.tax.service.gov.uk/browse/SASS-1546)

Implemented other equipment expenses page.

---

app/controllers/expenses/OtherEquipmentAmountController.scala
app/views/employment/CheckEmploymentExpensesViewEOY.scala.html
app/views/expenses/OtherEquipmentAmountView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/employment/CheckEmploymentExpensesControllerISpec.scala
it/controllers/expenses/OtherEquipmentAmountControllerISpec.scala

Create 'how much do you want to claim for buying other equipment' amount EOY page
https://jira.tools.tax.service.gov.uk/browse/SASS-1547

SASS-1547 - create expenses other equipment amount page

---

app/controllers/benefits/reimbursed/NonTaxableCostsBenefitsController.scala
app/models/benefits/ReimbursedCostsVouchersAndNonCashModel.scala
app/services/RedirectService.scala
app/views/benefits/reimbursed/NonTaxableCostsBenefitsView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/reimbursed/NonTaxableCostsBenefitsControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
test/models/benefits/ReimbursedCostsVouchersAndNonCashModelSpec.scala
test/services/RedirectServiceSpec.scala

https://jira.tools.tax.service.gov.uk/browse/SASS-1648

Added non taxable page

---

app/controllers/benefits/reimbursed/VouchersBenefitsAmountController.scala
app/models/benefits/ReimbursedCostsVouchersAndNonCashModel.scala
app/views/benefits/reimbursed/VouchersBenefitsAmountView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/reimbursed/VouchersBenefitsAmountControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
project/plugins.sbt
test/models/benefits/ReimbursedCostsVouchersAndNonCashModelSpec.scala
test/services/RedirectServiceSpec.scala

- Added vouchers benefits amount page
- Linking the page to the CYA page
https://jira.tools.tax.service.gov.uk/browse/SASS-1653

SASS-1653: Adding the vouchers benefits amount page

---

app/views/benefits/medical/ChildcareBenefitsView.scala.html
app/views/expenses/EmploymentExpensesView.scala.html
app/views/expenses/ProfessionalFeesAndSubscriptionsExpensesView.scala.html
app/views/expenses/UniformsOrToolsExpensesView.scala.html
app/views/templates/InternalServerErrorTemplate.scala.html
app/views/templates/NotFoundTemplate.scala.html
app/views/templates/ServiceUnavailableTemplate.scala.html
app/views/templates/TaxYearErrorTemplate.scala.html
app/views/templates/UnauthorisedUserErrorPageView.scala.html
app/views/templates/helpers/Link.scala.html

Added No Refferer attributes to Blank target links
[SASS-1721](https://jira.tools.tax.service.gov.uk/browse/SASS-1721)

SASS-1721 : added no refferer link to blank target urls

---

app/views/benefits/medical/ChildcareBenefitsView.scala.html
app/views/expenses/EmploymentExpensesView.scala.html
app/views/expenses/ProfessionalFeesAndSubscriptionsExpensesView.scala.html
app/views/expenses/UniformsOrToolsExpensesView.scala.html
app/views/templates/InternalServerErrorTemplate.scala.html
app/views/templates/NotFoundTemplate.scala.html
app/views/templates/ServiceUnavailableTemplate.scala.html
app/views/templates/TaxYearErrorTemplate.scala.html
app/views/templates/UnauthorisedUserErrorPageView.scala.html
app/views/templates/helpers/Link.scala.html

[SASS-1721](https://jira.tools.tax.service.gov.uk/browse/SASS-1721)

SASS-1721b : fixed spelling mistake

---

app/controllers/benefits/reimbursed/VouchersBenefitsController.scala
app/models/benefits/ReimbursedCostsVouchersAndNonCashModel.scala
app/services/RedirectService.scala
app/views/benefits/reimbursed/VouchersBenefitsView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/reimbursed/VouchersBenefitsControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
test/models/benefits/ReimbursedCostsVouchersAndNonCashModelSpec.scala
test/services/RedirectServiceSpec.scala

https://jira.tools.tax.service.gov.uk/browse/SASS-1652

SASS-1652 Added vouchers and credit cards page

---

app/controllers/benefits/reimbursed/NonCashBenefitsAmountController.scala
app/models/benefits/ReimbursedCostsVouchersAndNonCashModel.scala
app/views/benefits/reimbursed/NonCashBenefitsAmountView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/reimbursed/NonCashBenefitsAmountControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
test/models/benefits/ReimbursedCostsVouchersAndNonCashModelSpec.scala
test/services/RedirectServiceSpec.scala

created non-cash employment benefits amount page
[SASS-1655](https://jira.tools.tax.service.gov.uk/browse/SASS-1655)

SASS-1655 - added non-cash benefits amount page

---

app/controllers/benefits/income/IncomeTaxBenefitsAmountController.scala
app/models/benefits/IncomeTaxAndCostsModel.scala
app/views/benefits/income/IncomeTaxBenefitsAmountView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/income/IncomeTaxBenefitsAmountControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
test/models/benefits/IncomeTaxAndCostsModelSpec.scala
test/services/RedirectServiceSpec.scala

Created Income Tax employment benefits amount EOY page.
[SASS-1592](https://jira.tools.tax.service.gov.uk/browse/SASS-1592)

SASS-1592 Create Income Tax employment benefits amount EOY page

---

app/controllers/benefits/reimbursed/OtherBenefitsAmountController.scala
app/models/benefits/ReimbursedCostsVouchersAndNonCashModel.scala
app/views/benefits/reimbursed/OtherBenefitsAmountView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/reimbursed/OtherBenefitsAmountControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
test/models/benefits/ReimbursedCostsVouchersAndNonCashModelSpec.scala

- added other benefits amount page
- link the page to the benefits CYA page
https://jira.tools.tax.service.gov.uk/browse/SASS-1657

SASS-1657: Added other benefits amount page

---

app/controllers/benefits/assets/AssetsBenefitsAmountController.scala
app/models/benefits/AssetsModel.scala
app/views/benefits/assets/AssetsBenefitsAmountView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/assets/AssetsBenefitsAmountControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
it/utils/IntegrationTest.scala
test/models/benefits/AssetsModelSpec.scala
test/services/RedirectServiceSpec.scala

- Added assets for use amount page
- Linked the page to the cya page
https://jira.tools.tax.service.gov.uk/browse/SASS-1720

SASS-1720 Added assets for use amount page

---

app/controllers/benefits/assets/AssetsBenefitsController.scala
app/models/benefits/AssetsModel.scala
app/services/RedirectService.scala
app/views/benefits/assets/AssetsBenefitsView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/assets/AssetsBenefitsControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
test/models/benefits/AssetsModelSpec.scala
test/services/RedirectServiceSpec.scala

created assets employment benefits page and the updated change link from benefits cya page
[SASS-1719](https://jira.tools.tax.service.gov.uk/browse/SASS-1719)

SASS-1719 - added assets benefits page

---

app/controllers/benefits/reimbursed/NonCashBenefitsController.scala
app/controllers/benefits/reimbursed/VouchersBenefitsAmountController.scala
app/models/benefits/ReimbursedCostsVouchersAndNonCashModel.scala
app/services/RedirectService.scala
app/views/benefits/reimbursed/NonCashBenefitsView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/reimbursed/NonCashBenefitsControllerISpec.scala
it/controllers/benefits/reimbursed/VouchersBenefitsAmountControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
test/models/benefits/ReimbursedCostsVouchersAndNonCashModelSpec.scala
test/services/RedirectServiceSpec.scala

Created the non-cash employment benefits radio button EOY page
[SASS-1654](https://jira.tools.tax.service.gov.uk/browse/SASS-1654)

SASS-1654 Create non-cash employment benefits radio button EOY page

---

app/controllers/benefits/income/IncomeTaxBenefitsAmountController.scala
app/controllers/benefits/income/IncomeTaxBenefitsController.scala
app/controllers/benefits/income/IncomeTaxOrIncurredCostsBenefitsController.scala
app/controllers/benefits/income/IncurredCostsBenefitsAmountController.scala
app/controllers/benefits/income/IncurredCostsBenefitsController.scala
app/services/RedirectService.scala
it/controllers/benefits/income/IncomeTaxBenefitsAmountControllerISpec.scala
it/controllers/benefits/income/IncomeTaxBenefitsControllerISpec.scala
it/controllers/benefits/income/IncomeTaxOrIncurredCostsControllerISpec.scala
it/controllers/benefits/income/IncurredCostsBenefitsAmountControllerISpec.scala
it/controllers/benefits/income/IncurredCostsBenefitsControllerISpec.scala
it/utils/IntegrationTest.scala
project/AppDependencies.scala

- Navigation for income section
https://jira.tools.tax.service.gov.uk/browse/SASS-1658

SASS-1658 - Navigation for income section

---

app/audit/ViewEmploymentExpensesAudit.scala
app/models/expenses/Expenses.scala
test/audit/ViewEmploymentExpensesSpec.scala

altered audit model
[SASS-1666](https://jira.tools.tax.service.gov.uk/browse/SASS-1666)

SASS-1666 Change audit event model

---

app/controllers/benefits/reimbursed/OtherBenefitsController.scala
app/models/benefits/ReimbursedCostsVouchersAndNonCashModel.scala
app/services/RedirectService.scala
app/views/benefits/reimbursed/OtherBenefitsView.scala.html
app/views/employment/CheckYourBenefitsViewEOY.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/benefits/reimbursed/NonCashBenefitsAmountControllerISpec.scala
it/controllers/benefits/reimbursed/OtherBenefitsControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
test/audit/ViewEmploymentExpensesSpec.scala
test/models/benefits/ReimbursedCostsVouchersAndNonCashModelSpec.scala
test/services/RedirectServiceSpec.scala

Created other employment benefits radio button EOY page
[SASS-1656](https://jira.tools.tax.service.gov.uk/browse/SASS-1656)

Sass 1656 Created other employment benefits radio button EOY page

---

README.md

updated README.md file
[SASS-1599](https://jira.tools.tax.service.gov.uk/browse/SASS-1599)

SASS-1599 updated README.md file

---

app/views/benefits/medical/ChildcareBenefitsView.scala.html
app/views/expenses/CheckEmploymentExpensesView.scala.html
app/views/expenses/EmploymentExpensesView.scala.html
app/views/expenses/ProfessionalFeesAndSubscriptionsExpensesView.scala.html
app/views/expenses/UniformsOrToolsExpensesView.scala.html
app/views/templates/AgentAuthErrorPageView.scala.html
app/views/templates/IndividualUnauthorisedView.scala.html
app/views/templates/InternalServerErrorTemplate.scala.html
app/views/templates/NotFoundTemplate.scala.html
app/views/templates/ServiceUnavailableTemplate.scala.html
app/views/templates/TaxYearErrorTemplate.scala.html
app/views/templates/UnauthorisedUserErrorPageView.scala.html
app/views/templates/YouNeedAgentServicesView.scala.html
app/views/templates/helpers/Link.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
it/controllers/expenses/UniformsOrToolsExpensesControllerISpec.scala
project/AppDependencies.scala

Tidied routes, messages and links
https://jira.tools.tax.service.gov.uk/browse/SASS-1600

SASS-1770 Tidied routes, messages and links

---

app/config/AppConfig.scala
app/config/ConfigKeys.scala
app/connectors/NrsConnector.scala
app/connectors/RawResponseReads.scala
app/connectors/httpParsers/NrsSubmissionHttpParser.scala
app/controllers/employment/CheckEmploymentDetailsController.scala
app/models/employment/DecodedAmendEmploymentDetailsPayload.scala
app/models/employment/DecodedCreateNewEmploymentDetailsPayload.scala
app/models/employment/DecodedNewEmploymentData.scala
app/models/employment/createUpdate/CreateUpdateEmploymentRequest.scala
app/services/NrsService.scala
conf/application.conf
it/connectors/NrsConnectorSpec.scala
it/utils/IntegrationTest.scala
test/config/MockAppConfig.scala
test/config/MockNrsService.scala
test/controllers/employment/CheckEmploymentDetailsControllerSpec.scala
test/services/NrsServiceSpec.scala

Connect the `income-tax-employment-frontend` service to the `income-tax-nrs-proxy` service.
[SASS-1095](https://jira.tools.tax.service.gov.uk/browse/SASS-1095)

SASS-1095: Connect Income Tax Employment FE MS with Income-Tax-NRS-Proxy MS

---

conf/messages
conf/messages.cy
it/controllers/benefits/assets/AssetsTransfersBenefitsAmountControllerISpec.scala

Fixed agent error messages on AssetsTransfersBenefitsAmountPage
[SASS-1853](https://jira.tools.tax.service.gov.uk/browse/SASS-1853)

Changed error messages for agents

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_interruption-page.scss
app/controllers/expenses/EmploymentExpensesController.scala
app/controllers/expenses/ExpensesInterruptPageController.scala
app/views/expenses/ExpensesInterruptPageView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/expenses/EmploymentExpensesControllerISpec.scala
it/controllers/expenses/ExpensesInterruptPageControllerISpec.scala

Expenses - Create interrupt page following 'do you want to claim employment expenses
[SASS-1670](https://jira.tools.tax.service.gov.uk/browse/SASS-1670)

SASS-1670 Create Expenses Interrupt Page

---

app/controllers/benefits/assets/AssetTransfersBenefitsController.scala
app/controllers/benefits/assets/AssetsBenefitsAmountController.scala
app/controllers/benefits/assets/AssetsBenefitsController.scala
app/controllers/benefits/assets/AssetsOrAssetTransfersBenefitsController.scala
app/controllers/benefits/assets/AssetsTransfersBenefitsAmountController.scala
app/models/benefits/AssetsModel.scala
app/views/employment/CheckYourBenefitsViewEOY.scala.html
it/controllers/benefits/assets/AssetTransfersBenefitsControllerISpec.scala
it/controllers/benefits/assets/AssetsBenefitsAmountControllerISpec.scala
it/controllers/benefits/assets/AssetsBenefitsControllerISpec.scala
it/controllers/benefits/assets/AssetsOrAssetTransfersBenefitsControllerISpec.scala
it/controllers/benefits/assets/AssetsTransfersBenefitsAmountControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
project/AppDependencies.scala
test/models/benefits/AssetsModelSpec.scala

- Navigation for assets section
https://jira.tools.tax.service.gov.uk/browse/SASS-1726

SASS-1726 Navigation for assets section

---

app/controllers/employment/CheckEmploymentDetailsController.scala
app/controllers/employment/CheckYourBenefitsController.scala
app/views/employment/CheckEmploymentDetailsView.scala.html
app/views/employment/CheckYourBenefitsView.scala.html
app/views/employment/EmploymentDetailsAndBenefitsView.scala.html
app/views/expenses/CheckEmploymentExpensesView.scala.html
app/views/templates/helpers/Button.scala.html
conf/messages
conf/messages.cy
it/controllers/employment/CheckEmploymentDetailsControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
it/controllers/employment/EmploymentDetailsAndBenefitsControllerISpec.scala
it/controllers/expenses/CheckEmploymentExpensesControllerISpec.scala
test/builders/models/employment/EmploymentSourceBuilder.scala
test/controllers/employment/CheckEmploymentDetailsControllerSpec.scala
test/controllers/employment/CheckYourBenefitsControllerSpec.scala

Adding buttons to check your employment details, expenses and benefits pages for in year
Journey tests (Need to be merged first) -> hmrc/income-tax-submission-journey-tests#115
[SASS-1357](https://jira.tools.tax.service.gov.uk/browse/SASS-1357)

SASS-1887b  Adding buttons to complete in year employment journey

---

app/connectors/parsers/CreateUpdateEmploymentDataHttpParser.scala
app/models/employment/CreatedEmployment.scala
app/services/EmploymentSessionService.scala
it/connectors/CreateUpdateEmploymentDataConnectorSpec.scala
test/config/MockCreateUpdateEmploymentDataConnector.scala
test/services/EmploymentSessionServiceSpec.scala

Covers the 'API to pass up employment ID after submitting employment details so that employment benefits can then be linked to the correct employment' part of https://jira.tools.tax.service.gov.uk/browse/SASS-1664

SASS-1664 Updated to handle employment id returned

---

app/config/AppConfig.scala
conf/application.conf

Adding the feature switch in preparation for all of the Student Loans pages.
[SASS-2065](https://jira.tools.tax.service.gov.uk/browse/SASS-2065)

[DM] [SASS-2065] Added featureswitch for Student Loans

---

app/controllers/employment/EmploymentDatesController.scala
app/forms/employment/EmploymentDatesForm.scala
app/models/employment/EmploymentDates.scala
app/views/employment/CheckEmploymentDetailsView.scala.html
app/views/employment/EmploymentDatesView.scala.html
app/views/templates/helpers/DateInput.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/employment/CheckEmploymentDetailsControllerISpec.scala
it/controllers/employment/EmploymentDatesControllerISpec.scala
it/utils/ViewHelpers.scala
test/builders/models/mongo/EmploymentDetailsBuilder.scala

Created the start/end date page
[SASS-1798](https://jira.tools.tax.service.gov.uk/browse/SASS-1798)

SASS-1798 Creation of employment start date/end date page

---

it/controllers/employment/AddEmploymentControllerISpec.scala
it/controllers/employment/CheckEmploymentDetailsControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
it/controllers/employment/EmployerLeaveDateControllerISpec.scala
it/controllers/employment/EmployerNameControllerISpec.scala
it/controllers/employment/EmployerPayAmountControllerISpec.scala
it/controllers/employment/EmployerPayrollIdControllerISpec.scala
it/controllers/employment/EmployerStartDateControllerISpec.scala
it/controllers/employment/EmploymentDetailsAndBenefitsControllerISpec.scala
it/controllers/employment/EmploymentSummaryControllerISpec.scala
it/controllers/employment/EmploymentTaxControllerISpec.scala
it/controllers/employment/MultipleEmploymentSummaryEOYControllerISpec.scala
it/controllers/employment/PayeRefControllerISpec.scala
it/controllers/employment/RemoveEmploymentControllerISpec.scala
it/controllers/employment/SingleEmploymentSummaryEOYControllerISpec.scala
it/controllers/employment/StillWorkingForEmployerControllerISpec.scala
it/controllers/expenses/BusinessTravelOvernightExpensesControllerISpec.scala
it/controllers/expenses/CheckEmploymentExpensesControllerISpec.scala
it/controllers/expenses/EmploymentExpensesControllerISpec.scala
it/controllers/expenses/ExpensesInterruptPageControllerISpec.scala
it/controllers/expenses/OtherEquipmentAmountControllerISpec.scala
it/controllers/expenses/OtherEquipmentControllerISpec.scala
it/controllers/expenses/ProfFeesAndSubscriptionsExpensesAmountControllerISpec.scala
it/controllers/expenses/ProfessionalFeesAndSubscriptionsExpensesControllerISpec.scala
it/controllers/expenses/TravelAndOvernightAmountControllerISpec.scala
it/controllers/expenses/UniformsOrToolsExpensesAmountControllerISpec.scala
it/controllers/expenses/UniformsOrToolsExpensesControllerISpec.scala
it/utils/PageUrls.scala

- Updating the employment/expenses folders of ISpecs to use the PageURls object to verify the urls being redirected to
https://jira.tools.tax.service.gov.uk/browse/SASS-1671

Sass 2069 - Updating the employment/expenses folders of ISpecs to use the PageURls object

---

app/controllers/employment/CheckYourBenefitsController.scala
app/controllers/expenses/CheckEmploymentExpensesController.scala
app/models/employment/AllEmploymentData.scala
app/views/employment/CheckYourBenefitsViewEOY.scala.html
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
it/controllers/expenses/CheckEmploymentExpensesControllerISpec.scala
it/helpers/SessionCookieCrumbler.scala
test/controllers/employment/CheckYourBenefitsControllerSpec.scala
test/models/employment/AllEmploymentDataSpec.scala

SASS-2017b Added full flow

---

app/models/employment/EmploymentSource.scala
app/models/employment/StudentLoans.scala
app/models/employment/StudentLoansCYAModel.scala
app/models/mongo/EmploymentCYAModel.scala
app/services/EncryptionService.scala
app/services/RedirectService.scala
app/services/studentLoans/StudentLoansService.scala
project/AppDependencies.scala
test/builders/models/mongo/EmploymentCYAModelBuilder.scala
test/builders/models/mongo/EmploymentUserDataBuilder.scala
test/models/StudentLoansCYAModelSpec.scala
test/services/studentLoans/StudentLoansServiceSpec.scala

[SASS-2067](https://jira.tools.tax.service.gov.uk/browse/SASS-2067)

[SASS-2067] StudentLoansCYAModel

---

app/services/studentLoans/StudentLoansService.scala
test/services/studentLoans/StudentLoansServiceSpec.scala

[SASS-2067](https://jira.tools.tax.service.gov.uk/browse/SASS-2067)

SASS-2067 studentLoan update fix

---

app/services/EmploymentSessionService.scala
app/views/employment/CheckEmploymentDetailsView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/employment/CheckEmploymentDetailsControllerISpec.scala
test/services/EmploymentSessionServiceSpec.scala

[SASS-2046](https://jira.tools.tax.service.gov.uk/browse/SASS-2046)

SASS-2046 - Employment details CYA page iterations.

---

app/controllers/employment/RemoveEmploymentController.scala
app/views/employment/RemoveEmploymentView.scala.html
conf/messages
conf/messages.cy
it/controllers/employment/RemoveEmploymentControllerISpec.scala
test/controllers/employment/RemoveEmploymentControllerSpec.scala

[SASS-2050](https://jira.tools.tax.service.gov.uk/browse/SASS-2050)

SASS-2050 - Removing an employment iteration.

---

app/views/expenses/ExpensesInterruptPageView.scala.html
app/views/templates/GovUkLayoutFullWidth.scala.html

Change blue interrupt screen to full width of page
[SASS-1864](https://jira.tools.tax.service.gov.uk/browse/SASS-1864)
- []  Have you run the journey tests? (where applicable)

SASS-1864 Change blue interrupt screen to full width of page

---

conf/messages
conf/messages.cy
it/controllers/employment/RemoveEmploymentControllerISpec.scala

Adds a word to a message.
[SASS-2050](https://jira.tools.tax.service.gov.uk/browse/SASS-2050)

SASS-2050 - FIX: Updates paragraph to include missing word.

---

app/controllers/employment/AddEmploymentController.scala
app/views/employment/AddEmploymentView.scala.html
conf/messages
conf/messages.cy
it/controllers/employment/AddEmploymentControllerISpec.scala

Changed employment to employer.
[SASS-2049](https://jira.tools.tax.service.gov.uk/browse/SASS-2049)

SASS-2049 Add an employer iteration

---

it/utils/EmploymentDatabaseHelper.scala

https://jira.tools.tax.service.gov.uk/browse/SASS-2198

SASS-2198 Updated to remove all records instead of drop db

---

project/AppDependencies.scala

Removed govuk-template from service. I went through several pages and saw no issues. Given no issues have arrisen in any of our services, this should be good to go.
[SASS-2083](https://jira.tools.tax.service.gov.uk/browse/SASS-2083) (parent ticket)

[DM] [SASS-2143] Removed deprecated dependency

---

app/controllers/studentLoans/UglAmountController.scala
app/views/studentLoans/UglAmountView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/studentLoans/UglAmountControllerISpec.scala
it/utils/PageUrls.scala

Undergraduate Loan Amount page created
[SASS-1701](https://jira.tools.tax.service.gov.uk/browse/SASS-1701)

SASS-1701 ugl amount page

---

app/controllers/studentLoans/StudentLoansQuestionController.scala
app/forms/studentLoans/StudentLoanQuestionForm.scala
app/views/studentLoans/StudentLoansCYAView.scala.html
app/views/studentLoans/StudentLoansQuestionView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/studentLoans/StudentLoansCYAControllerISpec.scala
it/controllers/studentLoans/StudentLoansQuestionControllerISpec.scala
it/utils/PageUrls.scala
test/forms/studentLoans/StudentLoansQuestionFormSpec.scala

[SASS-1092](https://jira.tools.tax.service.gov.uk/browse/SASS-1092)

[SASS-1092] studentLoan Question page

---

conf/messages
conf/messages.cy
it/controllers/studentLoans/StudentLoansQuestionControllerISpec.scala

[SASS-1092](https://jira.tools.tax.service.gov.uk/browse/SASS-1092)

[SASS-1092] studentLoans Question typo fix

---

app/controllers/studentLoans/StudentLoansCYAController.scala
app/services/studentLoans/StudentLoansCYAService.scala
conf/app.routes
it/controllers/studentLoans/StudentLoansCYAControllerISpec.scala

Minor changes to the flow for the page.
[SASS-1860](SASS-1860)

[DM] [SASS-1860] Updated show redirect

---

app/audit/AmendEmploymentBenefitsUpdateAudit.scala
app/audit/CreateNewEmploymentBenefitsAudit.scala
app/audit/CreateNewEmploymentDetailsAudit.scala
app/controllers/employment/CheckYourBenefitsController.scala
app/models/employment/createUpdate/CreateUpdateEmploymentRequest.scala
app/services/employment/CheckYourBenefitsService.scala
test/audit/AmendEmploymentBenefitsUpdateAuditSpec.scala
test/audit/CreateNewEmploymentBenefitsAuditSpec.scala
test/config/MockCheckYourBenefitsService.scala
test/controllers/employment/CheckYourBenefitsControllerSpec.scala
test/services/employment/CheckYourBenefitsServiceSpec.scala

Created AmendEmploymentBenefitsUpdate audit event and CreateNewEmploymentBenefits audit event
[SASS-1818 and SASS-1819](https://jira.tools.tax.service.gov.uk/browse/SASS-1818
https://jira.tools.tax.service.gov.uk/browse/SASS-1819)

SASS-1818 Added Create and Amend Benefits Audit Events

---

app/config/AppConfig.scala
app/controllers/employment/CheckEmploymentDetailsController.scala
app/controllers/employment/CheckYourBenefitsController.scala
app/controllers/studentLoans/StudentLoansCYAController.scala
app/models/employment/CyaAndPrior.scala
app/models/employment/OptionalCyaAndPrior.scala
app/services/EmploymentSessionService.scala
app/services/studentLoans/StudentLoansCYAService.scala
conf/application.conf
it/controllers/employment/CheckEmploymentDetailsControllerISpec.scala
it/controllers/studentLoans/StudentLoansCYAControllerISpec.scala
it/utils/IntegrationTest.scala
project/AppDependencies.scala
test/config/MockAppConfig.scala
test/config/MockEmploymentSessionService.scala
test/config/MockStudentLoansCYAService.scala
test/controllers/employment/CheckEmploymentDetailsControllerSpec.scala
test/controllers/employment/CheckYourBenefitsControllerSpec.scala
test/controllers/studentLoans/StudentLoansCYAControllerSpec.scala
test/services/EmploymentSessionServiceSpec.scala

https://jira.tools.tax.service.gov.uk/browse/SASS-2333
Merge all 3 config before this one
https://github.com/hmrc/app-config-base/pull/6801/files
https://github.com/hmrc/app-config-qa/pull/14268/files
https://github.com/hmrc/app-config-production/pull/13873

SASS-2359 Added mimicking of apis for stubbed environments

---

app/audit/ViewStudentLoansDeductionsAudit.scala
app/controllers/studentLoans/StudentLoansCYAController.scala
app/services/studentLoans/StudentLoansCYAService.scala
test/audit/ViewStudentLoansDeductionsAuditSpec.scala
test/services/studentLoans/StudentLoansCYAServiceSpec.scala

Add audit event for viewing student loans deductions.
[SASS-1811](https://jira.tools.tax.service.gov.uk/browse/SASS-1811)

SASS-1811: ViewStudentLoansDeductions Audit Event

---

app/audit/DeleteEmploymentExpensesAudit.scala
app/models/employment/AllEmploymentData.scala
app/services/DeleteOrIgnoreExpensesService.scala
test/audit/DeleteEmploymentExpensesAuditSpec.scala
test/services/DeleteOrIgnoreExpensesServiceSpec.scala

Delete Employment Expenses audit event
[SASS-2002](https://jira.tools.tax.service.gov.uk/browse/SASS-2002)

SASS-2002 Delete Employment Expense audit event

---

app/services/studentLoans/StudentLoansCYAService.scala

[SASS-1812](https://jira.tools.tax.service.gov.uk/browse/SASS-1812)

SASS-1812a CreateNewStudentLoansDeductions audit 

---

app/views/employment/EmployerInformationView.scala.html

Update the text tags on the employer information page to use the govuk tags instead.
[SASS-2045](https://jira.tools.tax.service.gov.uk/browse/SASS-2045) (parent ticket)

[DM] [SASS-2432] Updated tags to use govuk tags

---

app/models/employment/DecodedDeleteEmploymentPayload.scala
app/services/employment/RemoveEmploymentService.scala
test/models/employment/DecodedDeleteEmploymentPayloadSpec.scala
test/services/RemoveEmploymentServiceSpec.scala

Amending DeleteEmployment audit event to include student loans in the payload
Parent ticket -> [SASS-2316](https://jira.tools.tax.service.gov.uk/browse/SASS-2316)

SASS-2441 Amend DeleteEmployment audit to include student loans

---

app/assets/stylesheets/application.scss

[SASS-2332](https://jira.tools.tax.service.gov.uk/browse/SASS-2332)

[SASS-2332] Back link and language toggle layout

---

app/assets/stylesheets/itsa-print.css
app/utils/RequestUtils.scala
app/views/templates/Head.scala.html
app/views/templates/Layout.scala.html
project/AppDependencies.scala

SASS-2523 fix to print preview styling.
[SASS-2523](https://jira.tools.tax.service.gov.uk/browse/SASS-2523)

SASS-2523 print preview styling

---

app/views/employment/EmployerNameView.scala.html
app/views/employment/EmployerPayAmountView.scala.html
app/views/employment/EmployerPayrollIdView.scala.html
app/views/employment/EmployerStartDateView.scala.html
app/views/employment/EmploymentDatesView.scala.html
app/views/employment/EmploymentTaxView.scala.html
app/views/employment/PayeRefView.scala.html
app/views/employment/SelectEmployerView.scala.html
app/views/employment/StillWorkingForEmployerView.scala.html
app/views/templates/helpers/DateInputAlt.scala.html
app/views/templates/helpers/InputRadioAlt.scala.html
app/views/templates/helpers/InputTextAlt.scala.html
it/controllers/employment/EmployerNameControllerISpec.scala
it/controllers/employment/EmployerPayAmountControllerISpec.scala
it/controllers/employment/EmployerPayrollIdControllerISpec.scala
it/controllers/employment/EmploymentDatesControllerISpec.scala
it/controllers/employment/EmploymentTaxControllerISpec.scala
it/controllers/employment/PayeRefControllerISpec.scala
it/controllers/employment/StillWorkingForEmployerControllerISpec.scala
test/views/employment/SelectEmployerViewSpec.scala

[SASS-2574](https://jira.tools.tax.service.gov.uk/browse/SASS-2574)

ASS-2574 - Page content inside for label for employment details.

---

app/views/employment/EmployerPayAmountView.scala.html

[SASS-2574](https://jira.tools.tax.service.gov.uk/browse/SASS-2574)

SASS-2574 - [FIX] Removes autocomplete field.

---

app/views/employment/CheckEmploymentDetailsView.scala.html
app/views/employment/CheckYourBenefitsView.scala.html
app/views/employment/EmployerInformationView.scala.html
app/views/employment/EmploymentSummaryView.scala.html
app/views/studentLoans/StudentLoansCYAView.scala.html
app/views/studentLoans/UglAmountView.scala.html
conf/messages
conf/messages.cy
it/controllers/employment/CheckEmploymentDetailsControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
it/controllers/employment/EmployerInformationControllerISpec.scala
it/controllers/employment/EmploymentSummaryControllerISpec.scala
it/controllers/studentLoans/PglAmountControllerISpec.scala
it/controllers/studentLoans/StudentLoansCYAControllerISpec.scala
it/controllers/studentLoans/StudentLoansQuestionControllerISpec.scala
it/controllers/studentLoans/UglAmountControllerISpec.scala
test/utils/TaxYearHelper.scala

Iterations to the student loans journey as well as employment iterations
[SASS-2517](https://jira.tools.tax.service.gov.uk/browse/SASS-2517)

SASS-2517 Student loans iterations

---

app/controllers/employment/CheckYourBenefitsController.scala
app/services/RedirectService.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
test/models/benefits/BenefitsViewModelSpec.scala
test/services/RedirectServiceSpec.scala

Fixed a bug in the journey navigation. I think the 3rd issue on the ticket has already been fixed.
[SASS-2575](https://jira.tools.tax.service.gov.uk/browse/SASS-2575)

SASS-2575 amended benefits journey to fix accessibility issue

---

app/actions/ActionsProvider.scala
app/config/AppConfig.scala
app/controllers/employment/CheckEmploymentDetailsController.scala
app/controllers/employment/CheckYourBenefitsController.scala
app/controllers/employment/EmployerInformationController.scala
app/controllers/employment/EmploymentSummaryController.scala
app/controllers/expenses/CheckEmploymentExpensesController.scala
app/controllers/studentLoans/PglAmountController.scala
app/controllers/studentLoans/StudentLoansCYAController.scala
app/controllers/studentLoans/StudentLoansQuestionController.scala
app/controllers/studentLoans/UglAmountController.scala
app/utils/InYearUtil.scala
conf/application.conf
it/controllers/employment/CheckEmploymentDetailsControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
it/controllers/expenses/CheckEmploymentExpensesControllerISpec.scala
project/AppDependencies.scala
test/actions/ActionsProviderSpec.scala
test/controllers/employment/CheckEmploymentDetailsControllerSpec.scala
test/controllers/employment/EmployerInformationControllerSpec.scala
test/controllers/employment/EmploymentSummaryControllerSpec.scala
test/controllers/studentLoans/PglAmountControllerSpec.scala
test/controllers/studentLoans/StudentLoansCYAControllerSpec.scala
test/controllers/studentLoans/StudentLoansQuestionControllerSpec.scala
test/controllers/studentLoans/UglAmountControllerSpec.scala
test/support/mocks/MockAppConfig.scala
test/support/mocks/MockStudentLoansService.scala
test/utils/InYearUtilSpec.scala

added feature switch for employment EOY
[SASS-2664](https://jira.tools.tax.service.gov.uk/browse/SASS-2664)

SASS-2664 - Turn off employment EOY functionality

---

app/controllers/expenses/RemoveExpensesController.scala
app/models/employment/AllEmploymentData.scala
app/services/CreateOrAmendExpensesService.scala
app/services/DeleteOrIgnoreExpensesService.scala
app/services/employment/RemoveEmploymentService.scala
test/models/employment/AllEmploymentDataSpec.scala

SASS-2762 Hiding ignored expenses

---

app/audit/UnignoreEmploymentAudit.scala
app/controllers/employment/CheckEmploymentDetailsController.scala
app/controllers/employment/CheckYourBenefitsController.scala
app/controllers/employment/EmployerInformationController.scala
app/controllers/employment/SelectEmployerController.scala
app/models/employment/AllEmploymentData.scala
app/services/UnignoreEmploymentService.scala
app/services/studentLoans/StudentLoansCYAService.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
it/controllers/employment/EmployerInformationControllerISpec.scala
test/controllers/employment/SelectEmployerControllerSpec.scala
test/models/employment/AllEmploymentDataSpec.scala
test/services/UnignoreEmploymentServiceSpec.scala
test/support/builders/models/employment/EmploymentDetailsViewModelBuilder.scala
test/support/builders/models/employment/UnignoreEmploymentNRSModelBuilder.scala
test/support/mocks/MockUnignoreEmploymentService.scala

[SASS-2720](https://jira.tools.tax.service.gov.uk/browse/SASS-2720)

SASS-2720 - Unignore employment audit event.

---

test/utils/TaxYearHelper.scala

[SASS-2720-Fix] Updated tax year helper

---

app/views/studentLoans/PglAmountView.scala.html
app/views/studentLoans/UglAmountView.scala.html
it/controllers/studentLoans/PglAmountControllerISpec.scala
it/controllers/studentLoans/UglAmountControllerISpec.scala

Updated SL amount page structure
[SASS-2482](https://jira.tools.tax.service.gov.uk/browse/SASS-2482)

[DM] [SASS-2482] updated SL amount page structure

---

app/controllers/studentLoans/PglAmountController.scala
app/controllers/studentLoans/StudentLoansQuestionController.scala
app/controllers/studentLoans/UglAmountController.scala
app/views/studentLoans/StudentLoansQuestionView.scala.html
it/controllers/studentLoans/StudentLoansQuestionControllerISpec.scala
test/controllers/studentLoans/PglAmountControllerSpec.scala
test/controllers/studentLoans/UglAmountControllerSpec.scala

Updated the question pages in Student Loans to restrict access to those who are in year.
[SASS-2745](https://jira.tools.tax.service.gov.uk/browse/SASS-2745)

[DM] [SASS-2745] Studen Loan question pages now restrict access when user is in year

---

app/forms/employment/EmployerNameForm.scala
app/forms/employment/EmployerPayrollIdForm.scala
app/forms/employment/EmploymentDateForm.scala
app/forms/employment/PayeForm.scala

[SASS-2874](https://jira.tools.tax.service.gov.uk/browse/SASS-2874)

SASS-2874 : added Input Filters to string input forms

---

app/controllers/employment/DidYouLeaveEmployerController.scala
app/controllers/employment/EmployerNameController.scala
app/controllers/employment/EmployerPayAmountController.scala
app/controllers/employment/EmployerPayrollIdController.scala
app/controllers/employment/EmployerStartDateController.scala
app/controllers/employment/EmploymentDatesController.scala
app/controllers/employment/EmploymentTaxController.scala
app/controllers/employment/PayeRefController.scala
app/models/mongo/EmploymentDetails.scala
app/services/RedirectService.scala
it/controllers/employment/DidYouLeaveEmployerControllerISpec.scala
it/controllers/employment/EmployerNameControllerISpec.scala
it/controllers/employment/EmployerPayrollIdControllerISpec.scala
test/models/mongo/EmploymentDetailsSpec.scala

[SASS-2755](https://jira.tools.tax.service.gov.uk/browse/SASS-2755)

SASS-2755 - Employment details navigation fix.

---

app/config/AppConfig.scala
app/controllers/tailorings/EmploymentGatewayController.scala
app/views/tailorings/EmploymentGatewayView.scala.html
conf/app.routes
conf/application.conf
conf/messages
conf/messages.cy
it/controllers/tailorings/EmploymentGatewayControllerISpec.scala
it/utils/IntegrationTest.scala
it/utils/PageUrls.scala
test/views/tailorings/EmploymentGatewayViewSpec.scala

[SASS-2895](https://jira.tools.tax.service.gov.uk/browse/SASS-2895)

[SASS-2895] Add employment gateway page

---

app/views/tailorings/EmploymentGatewayView.scala.html
test/views/tailorings/EmploymentGatewayViewSpec.scala

gateway caption fix

---

app/views/employment/CheckEmploymentDetailsView.scala.html
conf/messages
conf/messages.cy
test/views/employment/CheckEmploymentDetailsViewSpec.scala

[SASS-2715](https://jira.tools.tax.service.gov.uk/browse/SASS-2715)

SASS-2715 - Hidden text for nightmare employment scenario

---

it/controllers/employment/CheckEmploymentDetailsControllerISpec.scala
it/controllers/employment/CheckYourBenefitsControllerISpec.scala
it/controllers/employment/EmployerInformationControllerISpec.scala
it/controllers/employment/EmploymentSummaryControllerISpec.scala
it/controllers/expenses/CheckEmploymentExpensesControllerISpec.scala
it/utils/IntegrationTest.scala
it/utils/ViewHelpers.scala
project/AppDependencies.scala
test/controllers/employment/SelectEmployerControllerSpec.scala

[SASS-3123](https://jira.tools.tax.service.gov.uk/browse/SASS-3123)

SASS-3123 - Update bootstrap-BE/FE-play-28 dependencies.

---

app/controllers/employment/CannotUpdateEmploymentController.scala
app/views/employment/CannotUpdateEmployment.scala.html
app/views/employment/CannotUpdateEmploymentView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/employment/CannotUpdateEmploymentISpec.scala
project/AppDependencies.scala
test/views/employment/EmploymentCannotUpdateViewSpec.scala

[added cannot update employment page](https://github.com/hmrc/income-tax-employment-frontend/commit/a68ba5724ebdc27cd5824d3b4ee5e034ae9fb7cd)

[SASS 3048] added cannot update employment page

---

app/audit/DeleteEmploymentAudit.scala
app/controllers/employment/RemoveEmploymentController.scala
app/services/employment/RemoveEmploymentService.scala
app/views/employment/RemoveEmploymentView.scala.html
conf/messages
conf/messages.cy
test/audit/DeleteEmploymentAuditSpec.scala
test/config/MessagesSpec.scala
test/controllers/employment/RemoveEmploymentControllerSpec.scala
test/services/RemoveEmploymentServiceSpec.scala
test/views/employment/RemoveEmploymentViewSpec.scala

[SASS-SASS-3133](https://jira.tools.tax.service.gov.uk/browse/SASS-3133)

SASS-3133: Remove Employment changes

---

app/controllers/employment/CheckEmploymentDetailsController.scala
app/views/employment/CheckEmploymentDetailsView.scala.html
conf/messages
conf/messages.cy
it/controllers/employment/CheckEmploymentDetailsControllerISpec.scala
test/controllers/employment/CheckEmploymentDetailsControllerSpec.scala
test/views/employment/CheckEmploymentDetailsViewSpec.scala

[SASS-3224](https://jira.tools.tax.service.gov.uk/browse/SASS-3224)

SASS-3224 - Change CYA page to only be shown if all data is complete

---

app/views/employment/EmploymentSummaryView.scala.html
test/views/employment/EmploymentSummaryViewSpec.scala

[SASS-3292](https://jira.tools.tax.service.gov.uk/browse/SASS-3292)

SASS-3292 correct alignment of change and remove links on summary page

---

app/views/employment/CheckEmploymentDetailsView.scala.html
conf/messages
conf/messages.cy
project/AppDependencies.scala
test/views/employment/CheckEmploymentDetailsViewSpec.scala

[SASS-3164](https://jira.tools.tax.service.gov.uk/browse/SASS-3164)

SASS-3164 - Hidden text for Employment details CYA page.

---

app/services/RedirectService.scala
app/views/templates/GovUkLayoutFullWidth.scala.html
app/views/templates/Head.scala.html
app/views/templates/Layout.scala.html
conf/application.conf
project/AppDependencies.scala

…yment FE.
[SASS-3165](https://jira.tools.tax.service.gov.uk/browse/SASS-3165)

SASS-3165 - Fix Misconfigured Content Security Policy (CSP) for employment FE

---

app/views/employment/EmploymentSummaryView.scala.html

SASS-3292 update value class

---

app/utils/ViewUtils.scala
app/views/employment/CheckEmploymentDetailsView.scala.html
test/utils/ViewUtilSpec.scala

[SASS-2886](https://jira.tools.tax.service.gov.uk/browse/SASS-2886)

SASS-2866: Refactor employment dates formatter

---

app/views/employment/RemoveEmploymentView.scala.html
test/views/employment/RemoveEmploymentViewSpec.scala

[SASS-3341](https://jira.tools.tax.service.gov.uk/browse/SASS-3341)

SASS-3341: Remove Employment Period page changes

---

app/actions/AuthorisedTaxYearAction.scala
app/controllers/details/DidYouLeaveEmployerController.scala
app/controllers/details/EmployerNameController.scala
app/controllers/details/EmployerPayAmountController.scala
app/controllers/details/EmployerPayrollIdController.scala
app/controllers/details/EmployerStartDateController.scala
app/controllers/details/EmploymentDatesController.scala
app/controllers/details/PayeRefController.scala
app/controllers/employment/CheckEmploymentDetailsController.scala
app/forms/details/EmployerPayrollIdForm.scala
app/forms/details/PayeRefForm.scala
app/models/details/EmploymentDetails.scala
app/models/employment/EmploymentDetailsViewModel.scala
conf/messages
conf/messages.cy
it/controllers/details/EmployerPayrollIdControllerISpec.scala
it/controllers/details/PayeRefControllerISpec.scala
it/controllers/employment/CheckEmploymentDetailsControllerISpec.scala
project/AppDependencies.scala
test/forms/details/EmployerPayrollIdFormSpec.scala
test/forms/details/PayeRefFormSpec.scala
test/models/details/EmploymentDetailsSpec.scala
test/views/details/EmployerPayrollIdViewSpec.scala
test/views/details/PayeRefViewSpec.scala

[SASS-3348](https://jira.tools.tax.service.gov.uk/browse/SASS-3348)

SASS-3348 - Employment CYA page iteration - Mandatory/optional fields.

---

app/controllers/details/DidYouLeaveEmployerController.scala
app/controllers/details/EmployerNameController.scala
app/controllers/details/EmployerPayAmountController.scala
app/controllers/details/EmployerPayrollIdController.scala
app/controllers/details/EmployerStartDateController.scala
app/controllers/details/EmploymentDatesController.scala
app/controllers/details/PayeRefController.scala
app/controllers/employment/CheckEmploymentDetailsController.scala
app/models/details/EmploymentDetails.scala
app/services/employment/EmploymentService.scala
test/models/details/EmploymentDetailsSpec.scala
test/services/employment/EmploymentServiceSpec.scala

…allow for optional data.
[SASS-3439](https://jira.tools.tax.service.gov.uk/browse/SASS-3439)

SASS-3439 - Save and continue for 'Check your employment details' to allow for optional data.

---

app/views/templates/helpers/Heading.scala.html
project/AppDependencies.scala
test/support/ViewHelper.scala
test/views/templates/helpers/HeadingSpec.scala

[SASS-2760](https://jira.tools.tax.service.gov.uk/browse/SASS-2760)

SASS-2760 upgrade the frontend library and fix the heading ordering swap as a consequence of the upgrade

---

app/actions/AuthorisedAction.scala
it/helpers/WireMockHelper.scala
it/utils/IntegrationTest.scala
test/actions/AuthorisedActionSpec.scala
test/support/mocks/MockAuthorisedAction.scala

Increase the 'Confidence Level' to 250 from 200
SASS-3946 https://jira.tools.tax.service.gov.uk/browse/SASS-3946

SASS-3946 Increase the 'Confidence Level' to 250 from 200

---

app/views/employment/EmploymentSummaryView.scala.html
project/plugins.sbt

Removed br tag and changed span tag to a p with no margin to still get a line break.
SASS-4094 (https://jira.tools.tax.service.gov.uk/browse/SASS-4094)

SASS-4094: R7C - Use CSS instead <br> tags for presentational purpose

---

project/AppDependencies.scala

Upgrade dependencies

---

app/controllers/benefits/accommodation/NonQualifyingRelocationBenefitsAmountController.scala
app/controllers/benefits/accommodation/NonQualifyingRelocationBenefitsController.scala
app/models/benefits/pages/NonQualifyingRelocationBenefitAmountPage.scala
app/models/benefits/pages/NonQualifyingRelocationBenefitsPage.scala
app/utils/RedirectsMapper.scala
app/views/benefits/accommodation/NonQualifyingRelocationBenefitsAmountView.scala.html
app/views/benefits/accommodation/NonQualifyingRelocationBenefitsView.scala.html
it/controllers/benefits/accommodation/NonQualifyingRelocationBenefitsAmountControllerISpec.scala
it/controllers/benefits/accommodation/NonQualifyingRelocationBenefitsControllerISpec.scala
test/controllers/benefits/accommodation/NonQualifyingRelocationBenefitsAmountControllerSpec.scala
test/controllers/benefits/accommodation/NonQualifyingRelocationBenefitsControllerSpec.scala
test/support/builders/models/benefits/pages/NonQualifyingRelocationBenefitAmountPageBuilder.scala
test/support/builders/models/benefits/pages/NonQualifyingRelocationBenefitsPageBuilder.scala
test/support/mocks/MockAccommodationService.scala
test/support/mocks/MockRedirectService.scala
test/utils/RedirectsMapperSpec.scala
test/views/benefits/accommodation/LivingAccommodationBenefitsAmountViewSpec.scala
test/views/benefits/accommodation/NonQualifyingRelocationBenefitsAmountViewSpec.scala
test/views/benefits/accommodation/NonQualifyingRelocationBenefitsViewSpec.scala

[SASS-4563](https://jira.tools.tax.service.gov.uk/browse/SASS-4563)

SASS-4563 [Refactoring] - NonQualifyingRelocationBenefitsAmountController and NonQualifyingRelocationBenefitsController should use Actions Builders

---

app/controllers/benefits/fuel/CompanyCarBenefitsAmountController.scala
app/controllers/benefits/fuel/CompanyCarBenefitsController.scala
app/models/benefits/pages/CompanyCarBenefitsAmountPage.scala
app/models/benefits/pages/CompanyCarBenefitsPage.scala
app/utils/RedirectsMapper.scala
app/views/benefits/fuel/CompanyCarBenefitsAmountView.scala.html
app/views/benefits/fuel/CompanyCarBenefitsView.scala.html
it/controllers/benefits/fuel/CarFuelBenefitsAmountControllerISpec.scala
it/controllers/benefits/fuel/CompanyCarBenefitsAmountControllerISpec.scala
it/controllers/benefits/fuel/CompanyCarBenefitsControllerISpec.scala
test/controllers/benefits/fuel/CompanyCarBenefitsAmountControllerSpec.scala
test/support/builders/models/benefits/pages/CompanyCarBenefitsAmountPageBuilder.scala
test/support/builders/models/benefits/pages/CompanyCarBenefitsPageBuilder.scala
test/support/mocks/MockFuelService.scala
test/support/mocks/MockRedirectService.scala
test/utils/RedirectsMapperSpec.scala
test/views/benefits/fuel/CompanyCarBenefitsAmountViewSpec.scala
test/views/benefits/fuel/CompanyCarBenefitsViewSpec.scala

[SASS-4588](https://jira.tools.tax.service.gov.uk/browse/SASS-4588)

SASS-4588 [Refactoring] - CompanyCarBenefitsController and CompanyCarBenefitsAmountController should use action builder

---

app/forms/details/EmployerNameForm.scala
app/forms/validation/StringConstraints.scala
app/views/details/EmployerNameView.scala.html
conf/messages
conf/messages.cy
test/forms/details/EmployerNameFormSpec.scala
test/views/details/EmployerNameViewSpec.scala

[SASS-4481](https://jira.tools.tax.service.gov.uk/browse/SASS-4481)

SASS-4481 update content for 'What's the name of your employer' page

---

app/views/studentLoans/PglAmountView.scala.html
app/views/studentLoans/UglAmountView.scala.html
conf/messages
conf/messages.cy
test/views/studentLoans/PglAmountViewSpec.scala
test/views/studentLoans/UglAmountViewSpec.scala

SASS-4657 Accessibility - Label in name

---

app/controllers/details/PayeRefController.scala
app/views/details/PayeRefView.scala.html
conf/application.conf
conf/messages
conf/messages.cy
project/AppDependencies.scala
test/views/details/PayeRefViewSpec.scala

[SASS-4487](https://jira.tools.tax.service.gov.uk/browse/SASS-4487)

SASS-4487 update content for 'What is the PAYE ref?' page

---

app/controllers/details/EmployerPayrollIdController.scala
app/forms/AmountForm.scala
app/forms/details/EmployerPayrollIdForm.scala
app/forms/details/EmploymentDetailsFormsProvider.scala
app/models/benefits/pages/EmployerPayrollIdPage.scala
app/models/employment/EmploymentDates.scala
app/views/details/EmployerPayrollIdView.scala.html
conf/messages
conf/messages.cy
it/controllers/details/EmployerPayrollIdControllerISpec.scala
test/controllers/details/EmployerPayrollIdControllerSpec.scala
test/forms/details/EmployerPayrollIdFormSpec.scala
test/models/benefits/pages/EmployerPayrollIdPageSpec.scala
test/support/builders/models/benefits/pages/EmployerPayrollIdPageBuilder.scala
test/support/mocks/MockEmploymentService.scala
test/views/details/EmployerPayrollIdViewSpec.scala

[SASS-4488](https://jira.tools.tax.service.gov.uk/browse/SASS-4488)

SASS-4488 - 'What is the Payroll ID?' page.

---

app/views/details/EmployerPayrollIdView.scala.html
test/views/details/EmployerPayrollIdViewSpec.scala

[FIX] Fixes reversed P45 and P60 messages.

---

app/connectors/TailoringDataConnector.scala
app/connectors/parsers/ClearExcludedJourneysHttpParser.scala
app/connectors/parsers/GetExcludedJourneysHttpParser.scala
app/connectors/parsers/PostExcludedJourneyHttpParser.scala
app/controllers/employment/EmploymentSummaryController.scala
app/controllers/tailorings/EmploymentGatewayController.scala
app/controllers/tailorings/RemoveAllEmploymentController.scala
app/models/tailoring/ExcludeJourneyModel.scala
app/models/tailoring/ExcludedJourneysResponseModel.scala
app/services/tailoring/TailoringService.scala
app/views/employment/EmploymentSummaryView.scala.html
app/views/tailorings/RemoveAllEmploymentView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/connectors/TailoringDataConnectorISpec.scala
it/controllers/employment/EmploymentSummaryControllerISpec.scala
it/controllers/tailorings/EmploymentGatewayControllerISpec.scala
it/controllers/tailorings/RemoveAllEmploymentControllerISpec.scala
it/utils/IntegrationTest.scala
it/utils/PageUrls.scala
test/controllers/employment/EmploymentSummaryControllerSpec.scala
test/services/tailorings/TailoringServiceSpec.scala
test/support/mocks/MockAppConfig.scala
test/support/mocks/MockTailoringConnector.scala
test/support/mocks/MockTailoringService.scala
test/views/employment/EmploymentSummaryViewSpec.scala
test/views/tailorings/RemoveAllEmploymentViewSpec.scala

[SASS-3388](https://jira.tools.tax.service.gov.uk/browse/SASS-3388)

[SASS-3388] Tailor employment

---

conf/application.conf

[NO-TICKET] Update defaultTaxYear to 2024

---

app/controllers/details/DidYouLeaveEmployerController.scala
app/controllers/details/EmployerEndDateController.scala
app/controllers/details/EmployerNameController.scala
app/controllers/details/PayeRefController.scala
app/forms/details/EmploymentDetailsFormsProvider.scala
app/models/benefits/pages/DidYouLeaveEmployerPage.scala
app/utils/InYearUtil.scala
app/utils/ViewUtils.scala
app/views/details/DidYouLeaveEmployerView.scala.html
app/views/details/EmployerPayAmountView.scala.html
app/views/details/EmploymentTaxView.scala.html
conf/messages
conf/messages.cy
it/controllers/details/DidYouLeaveEmployerControllerISpec.scala
it/controllers/details/EmployerNameControllerISpec.scala
it/controllers/details/PayeRefControllerISpec.scala
test/controllers/details/DidYouLeaveEmployerControllerSpec.scala
test/controllers/details/EmployerEndDateControllerSpec.scala
test/forms/details/EmploymentDetailsFormsProviderSpec.scala
test/models/benefits/pages/AssetsOrAssetTransfersBenefitsPageSpec.scala
test/models/benefits/pages/DidYouLeaveEmployerPageSpec.scala
test/support/builders/models/benefits/pages/DidYouLeaveEmployerPageBuilder.scala
test/support/mocks/MockEmploymentService.scala
test/utils/InYearUtilSpec.scala
test/utils/ViewUtilSpec.scala
test/views/details/DidYouLeaveEmployerViewSpec.scala
test/views/details/EmployerPayAmountViewSpec.scala
test/views/details/EmploymentTaxViewSpec.scala

[SASS-4484](https://jira.tools.tax.service.gov.uk/browse/SASS-4484)

SASS-4484 - 'Did you leave employer between' page.

---

app/views/employment/CheckEmploymentDetailsView.scala.html
conf/messages
conf/messages.cy
test/views/employment/CheckEmploymentDetailsViewSpec.scala

[SASS-4718](https://jira.tools.tax.service.gov.uk/browse/SASS-4718)

SASS-4718 Employment changes update CYA

---

app/views/details/EmployerEndDateView.scala.html
app/views/details/EmployerStartDateView.scala.html
app/views/details/EmploymentDatesView.scala.html
conf/messages
conf/messages.cy
test/views/details/EmployerEndDateViewSpec.scala
test/views/details/EmployerStartDateViewSpec.scala

[SASS-4615-Implement dynamic date example]  (https://jira.tools.tax.service.gov.uk/browse/SASS-4615)

SASS-4615 Implement dynamic date example

---

app/views/employment/EmploymentSummaryView.scala.html

[SASS-4962] https://jira.tools.tax.service.gov.uk/browse/SASS-4962

SASS-4962 Amend welsh content

---

app/views/employment/CheckEmploymentDetailsView.scala.html

[SASS-4992](https://jira.tools.tax.service.gov.uk/browse/SASS-4992)

SASS-4992 fix dates slipping onto the next row

---

app/controllers/employment/EmployerInformationController.scala

SASS-5070 - fix not showing page

---

app/models/employment/EmploymentData.scala
build.sbt
conf/application.conf
it/controllers/employment/CheckEmploymentDetailsControllerISpec.scala
it/controllers/studentLoans/PglAmountControllerISpec.scala
it/controllers/studentLoans/StudentLoansCYAControllerISpec.scala
project/AppDependencies.scala
project/plugins.sbt
test/audit/AmendEmploymentDetailsUpdateAuditSpec.scala
test/controllers/employment/EmploymentSummaryControllerSpec.scala
test/controllers/employment/RemoveEmploymentControllerSpec.scala
test/services/DeleteOrIgnoreExpensesServiceSpec.scala
test/services/EmploymentSessionServiceSpec.scala
test/services/employment/CheckEmploymentDetailsServiceSpec.scala
test/services/employment/CheckYourBenefitsServiceSpec.scala
test/services/expenses/CheckEmploymentExpensesServiceSpec.scala
test/services/studentLoans/StudentLoansCYAServiceSpec.scala
test/services/tailorings/TailoringServiceSpec.scala
test/support/builders/models/employment/EmploymentDataBuilder.scala

Adding offPayrollWorker field.
[SASS-5554](https://jira.tools.tax.service.gov.uk/browse/SASS-5554)

SASS-5554: Get Employment Detail View

---

app/models/employment/createUpdate/CreateUpdateEmploymentRequest.scala
it/connectors/CreateUpdateEmploymentDataConnectorSpec.scala

SASS-5555 Create Update employment detail override 1935

---

project/AppDependencies.scala

SASS-7277: upgrade play-frontend-hmrc-play

---

app/views/employment/CheckEmploymentDetailsView.scala.html

SASS-7554: HTML injection issue on Employment payroll ID question page

---

app/audit/AmendEmploymentDetailsUpdateAudit.scala
app/audit/ViewEmploymentDetailsAudit.scala
app/models/employment/createUpdate/CreateUpdateEmploymentRequest.scala
test/audit/AmendEmploymentDetailsUpdateAuditSpec.scala
test/services/employment/CheckEmploymentDetailsServiceSpec.scala

SASS-7212: Amend Event for OPW Journey

---

app/views/studentLoans/StudentLoansQuestionView.scala.html
app/views/templates/helpers/DateInput.scala.html
app/views/templates/helpers/InputRadio.scala.html
app/views/templates/helpers/InputText.scala.html
build.sbt
conf/logback.xml
project/plugins.sbt
test/support/ViewHelper.scala

SASS-9198 | Fix Error prefix not being translated

---

app/utils/ViewUtils.scala

SASS-10112: updating viewutils to remove ariaHidden

---

app/connectors/SectionCompletedConnector.scala
it/test/connectors/SectionCompletedConnectorISpec.scala
it/test/services/SectionCompletedServiceISpec.scala

fixed routes for journey answers

---

app/actions/AuthorisedAction.scala
it/test/utils/IntegrationTest.scala
test/actions/AuthorisedActionSpec.scala
test/support/mocks/MockAuthorisedAction.scala

[SASS-10774] Handle non-Auth exceptions in AuthAction and render ISE
